// Swift syntax helpers for the generated DSTokens sources (ARCHITECTURE §3.1 `formats/swift/syntax.ts`):
// identifier escaping, type names, doc comments and the file layout (§12 rule 5: UTF-8, LF, one final
// newline, no trailing whitespace). Literals come from the renderers of transforms/ (§7); nothing here
// formats a number itself.
import { lowerCamel } from '../../ir/naming.ts';
import { swiftString } from '../../transforms/font.ts';
import { BUILD_COMMAND } from '../header.ts';

export { swiftString };

/** Reserved words that need backticks when used as an identifier (declarations and case names). */
const SWIFT_RESERVED = new Set([
  'associatedtype', 'class', 'deinit', 'enum', 'extension', 'fileprivate', 'func', 'import', 'init', 'inout', 'internal',
  'let', 'open', 'operator', 'private', 'precedencegroup', 'protocol', 'public', 'rethrows', 'static', 'struct', 'subscript',
  'typealias', 'var', 'break', 'case', 'catch', 'continue', 'default', 'defer', 'do', 'else', 'fallthrough', 'for', 'guard',
  'if', 'in', 'repeat', 'return', 'throw', 'switch', 'where', 'while', 'Any', 'as', 'await', 'false', 'is', 'nil', 'self',
  'Self', 'super', 'throws', 'true', 'try', 'package', 'consume', 'borrowing', 'consuming', 'copy', 'discard', 'each', 'some', 'any',
]);

/** `name` as a declared identifier: backticked when it is a reserved word. */
export function ident(name: string): string {
  const bare = name.replace(/^`|`$/g, '');
  return SWIFT_RESERVED.has(bare) ? `\`${bare}\`` : bare;
}

/** The identifier without backticks (for names built from other names). */
export function bareIdent(name: string): string {
  return name.replace(/^`|`$/g, '');
}

/** UpperCamel of kebab or camel segments: ['glass', 'dark'] → 'GlassDark'; 'zIndex' → 'ZIndex'. */
export function upperCamel(segments: readonly string[]): string {
  const camel = lowerCamel(segments);
  return camel.charAt(0).toUpperCase() + camel.slice(1);
}

/** The static header every generated Swift file starts with (§12 rule 4: no volatile content). */
export function swiftHeader(source: string): string {
  return `// Generated by tools/tokens from ${source}. Do not edit; run ${BUILD_COMMAND}.`;
}

/**
 * `///` lines for a `$description` and the `@available(*, deprecated, …)` attribute for `$deprecated`
 * (ARCHITECTURE §9.11), indented by `indent`.
 */
export function docLines(description: string | null, deprecated: string | true | null, indent: string): string[] {
  const out: string[] = [];
  if (description !== null) {
    for (const line of description.split(/\r?\n/)) out.push(`${indent}///${line.trim() === '' ? '' : ` ${line.trim()}`}`);
  }
  if (deprecated !== null) {
    out.push(deprecated === true ? `${indent}@available(*, deprecated)` : `${indent}@available(*, deprecated, message: ${swiftString(deprecated)})`);
  }
  return out;
}

/** Joins lines into a file: LF, no trailing whitespace, exactly one final newline. */
export function swiftFile(lines: readonly string[]): string {
  const text = lines.map((l) => l.replace(/[ \t]+$/, '')).join('\n').replace(/\n+$/, '');
  return `${text}\n`;
}
