// swift-tools-version: 6.2
// Prism — multi-platform design system (SwiftUI side).
// The manifest lives at the repository root because SwiftPM resolves URL
// dependencies from the repository root (ADR-0014); sources live under swift/.
import PackageDescription

let uiSettings: [SwiftSetting] = [
    .swiftLanguageMode(.v6),
    // UI targets are main-actor by default (PackageDescription 6.2); DSTokens stays nonisolated.
    .defaultIsolation(MainActor.self),
    .define("DS_GLASS", .when(platforms: [.iOS, .macOS, .macCatalyst])),
]

let valueSettings: [SwiftSetting] = [
    .swiftLanguageMode(.v6),
]

let package = Package(
    name: "Prism",
    defaultLocalization: "en",
    platforms: [.iOS(.v26), .macOS(.v26), .watchOS(.v26)],
    products: [
        .library(name: "DSTokens", targets: ["DSTokens"]),
        .library(name: "DSIcons", targets: ["DSIcons"]),
        .library(name: "DSCore", targets: ["DSCore"]),
        .library(name: "DSComponents", targets: ["DSComponents"]),
        .library(name: "DSCharts", targets: ["DSCharts"]),
        // The showcase app's view layer; a product so the generated Xcode project can link it (docs/showcase.md).
        .library(name: "DSShowcase", targets: ["DSShowcase"]),
    ],
    dependencies: [
        // Test-only: snapshot rendering of SwiftUI views (MIT).
        .package(url: "https://github.com/pointfreeco/swift-snapshot-testing", from: "1.19.4"),
    ],
    targets: [
        // Generated by the token build (tools/tokens), except DSTokens.swift and its version constant. Never hand-edit Generated/ or Resources/.
        // Resources, both generated: the color catalog, one namespace folder per brand (ADR-0020 §7), compiled
        // by actool under xcodebuild; the font files every brand bundles on Apple with their OFL.txt, copied
        // with their folders (ADR-0021 §11).
        .target(
            name: "DSTokens",
            path: "swift/Sources/DSTokens",
            resources: [.process("Resources/Colors.xcassets"), .copy("Resources/Fonts")],
            swiftSettings: valueSettings
        ),
        // Generated by tools/icons from spec/icons/registry.json (roadmap P2-2, ADR-0013). Never hand-edit
        // Generated/ or Resources/. Resources: the image sets generated from the Phosphor cuts for the icons
        // Apple has no fitting SF Symbol for, with `preserves-vector-representation` and the template
        // rendering intent, plus the Phosphor licence they are redistributed under (critic G-09).
        .target(
            name: "DSIcons",
            path: "swift/Sources/DSIcons",
            resources: [.process("Resources/Icons.xcassets"), .copy("Resources/Phosphor-LICENSE.txt")],
            swiftSettings: valueSettings
        ),
        // Theme, environment, accessibility policy, surface resolution, font registration, haptics, motion.
        .target(
            name: "DSCore",
            dependencies: ["DSTokens"],
            path: "swift/Sources/DSCore",
            swiftSettings: uiSettings
        ),
        // Surface, Text, Button and Card (P3-3); DSTokens directly, since components name `DSTokenSet` members.
        .target(
            name: "DSComponents",
            dependencies: ["DSTokens", "DSCore", "DSIcons"],
            path: "swift/Sources/DSComponents",
            swiftSettings: uiSettings
        ),
        .target(
            name: "DSCharts",
            dependencies: ["DSCore"],
            path: "swift/Sources/DSCharts",
            swiftSettings: uiSettings
        ),
        // Everything the showcase app is made of except its twenty-line shell (docs/showcase.md): the generated token
        // and component catalogues, the example renderers, the screens and the axis bar. It is a package target so
        // that `swift build` and the two `xcodebuild build -scheme Prism-Package` steps compile it — a component
        // that lands without its renderer must fail in CI, not only on the machine that runs the app. The screens
        // are `#if os(iOS) || os(macOS)`: the owner asked for a macOS/iOS app, and the watch has no split view.
        .target(
            name: "DSShowcase",
            dependencies: ["DSTokens", "DSCore", "DSComponents", "DSIcons"],
            path: "swift/Showcase/Sources/DSShowcase",
            swiftSettings: uiSettings
        ),
        // Host-runnable (`swift test` on macOS): token parity, contrast math, surface rules, spring conversions.
        .testTarget(
            name: "DSTokensTests",
            dependencies: ["DSTokens"],
            path: "swift/Tests/DSTokensTests",
            swiftSettings: valueSettings
        ),
        .testTarget(
            name: "DSCoreTests",
            dependencies: ["DSCore"],
            path: "swift/Tests/DSCoreTests",
            swiftSettings: uiSettings
        ),
        // Host-runnable (`swift test` on macOS): the manifest and examples against the specs, component bindings,
        // geometry rules and the count-up rule (P3-3). No test here reads pixels: `swift test` copies
        // Colors.xcassets uncompiled, so every token color resolves to nothing and renders clear.
        .testTarget(
            name: "DSComponentsTests",
            dependencies: ["DSTokens", "DSCore", "DSComponents"],
            path: "swift/Tests/DSComponentsTests",
            swiftSettings: uiSettings
        ),
        // The P3-3 snapshots of every spec example, compared on the iPhone 17 simulator on iOS 26.5 (`xcodebuild test
        // -only-testing:DSSnapshotTests`) against the baselines in __Snapshots__, named for the gallery pairing (P3-5).
        // Every pixel-reading suite lives here too (Surface, Button, the Reduce Motion press, the figures
        // override), `#if os(iOS)`, because only a simulator run compiles the color catalog;
        // the equal-width figures of ADR-0021 §5 and the matrix checks also run on the macOS host. README.md explains.
        .testTarget(
            name: "DSSnapshotTests",
            dependencies: [
                "DSTokens",
                "DSCore",
                "DSComponents",
                "DSCharts",
                .product(name: "SnapshotTesting", package: "swift-snapshot-testing"),
            ],
            path: "swift/Tests/DSSnapshotTests",
            exclude: ["__Snapshots__", "README.md"],
            swiftSettings: uiSettings
        ),
    ]
)
