// swift-tools-version: 6.2
// Prism — multi-platform design system (SwiftUI side).
// The manifest lives at the repository root because SwiftPM resolves URL
// dependencies from the repository root (ADR-0014); sources live under swift/.
import PackageDescription

let uiSettings: [SwiftSetting] = [
    .swiftLanguageMode(.v6),
    // UI targets are main-actor by default (PackageDescription 6.2); DSTokens stays nonisolated.
    .defaultIsolation(MainActor.self),
    .define("DS_GLASS", .when(platforms: [.iOS, .macOS, .macCatalyst])),
]

let valueSettings: [SwiftSetting] = [
    .swiftLanguageMode(.v6),
]

let package = Package(
    name: "Prism",
    defaultLocalization: "en",
    platforms: [.iOS(.v26), .macOS(.v26), .watchOS(.v26)],
    products: [
        .library(name: "DSTokens", targets: ["DSTokens"]),
        .library(name: "DSIcons", targets: ["DSIcons"]),
        .library(name: "DSCore", targets: ["DSCore"]),
        .library(name: "DSComponents", targets: ["DSComponents"]),
        .library(name: "DSCharts", targets: ["DSCharts"]),
    ],
    dependencies: [
        // Test-only: snapshot rendering of SwiftUI views (MIT).
        .package(url: "https://github.com/pointfreeco/swift-snapshot-testing", from: "1.19.4"),
    ],
    targets: [
        // Generated by the token build (tools/tokens), except DSTokens.swift and its version constant. Never hand-edit Generated/ or Resources/.
        // Resources, both generated: the color catalog, one namespace folder per brand (ADR-0020 §7), compiled
        // by actool under xcodebuild; the font files every brand bundles on Apple with their OFL.txt, copied
        // with their folders (ADR-0021 §11).
        .target(
            name: "DSTokens",
            path: "swift/Sources/DSTokens",
            resources: [.process("Resources/Colors.xcassets"), .copy("Resources/Fonts")],
            swiftSettings: valueSettings
        ),
        // Generated by tools/icons from spec/icons/registry.json (roadmap P2-2, ADR-0013). Never hand-edit
        // Generated/ or Resources/. Resources: the image sets generated from the Phosphor cuts for the icons
        // Apple has no fitting SF Symbol for, with `preserves-vector-representation` and the template
        // rendering intent, plus the Phosphor licence they are redistributed under (critic G-09).
        .target(
            name: "DSIcons",
            path: "swift/Sources/DSIcons",
            resources: [.process("Resources/Icons.xcassets"), .copy("Resources/Phosphor-LICENSE.txt")],
            swiftSettings: valueSettings
        ),
        // Theme, environment, accessibility policy, surface resolution, font registration, haptics, motion.
        .target(
            name: "DSCore",
            dependencies: ["DSTokens"],
            path: "swift/Sources/DSCore",
            swiftSettings: uiSettings
        ),
        .target(
            name: "DSComponents",
            dependencies: ["DSCore", "DSIcons"],
            path: "swift/Sources/DSComponents",
            swiftSettings: uiSettings
        ),
        .target(
            name: "DSCharts",
            dependencies: ["DSCore"],
            path: "swift/Sources/DSCharts",
            swiftSettings: uiSettings
        ),
        // Host-runnable (`swift test` on macOS): token parity, contrast math, surface rules, spring conversions.
        .testTarget(
            name: "DSTokensTests",
            dependencies: ["DSTokens"],
            path: "swift/Tests/DSTokensTests",
            swiftSettings: valueSettings
        ),
        .testTarget(
            name: "DSCoreTests",
            dependencies: ["DSCore"],
            path: "swift/Tests/DSCoreTests",
            swiftSettings: uiSettings
        ),
        // Simulator-only (`xcodebuild test`): SwiftUI snapshots paired with the web gallery by example id.
        .testTarget(
            name: "DSSnapshotTests",
            dependencies: [
                "DSComponents",
                "DSCharts",
                .product(name: "SnapshotTesting", package: "swift-snapshot-testing"),
            ],
            path: "swift/Tests/DSSnapshotTests",
            exclude: ["__Snapshots__"],
            swiftSettings: uiSettings
        ),
    ]
)
