import SwiftUI
import DSShowcase

/// The whole app shell: a window, the showcase root inside it, and on the Mac the one menu command the frame owns.
///
/// Everything with logic in it lives in `DSShowcase`, which `swift build` and the two
/// `xcodebuild build -scheme Prism-Package` steps already compile (docs/showcase.md §5), so what CI does not
/// build is these few lines. The Xcode project that wraps them is generated by `tools/showcase/apple` and is not
/// committed, exactly as `fixtures/swiftui-app`'s is not.
@main
struct PrismShowcaseApp: App {
    /// Shared with `DSShowcaseCommands` so that **View ▸ Axes** (⌘⇧A) and the toolbar button every screen carries
    /// open the same sheet. A `Scene`'s commands cannot reach the view tree's own state, so the state starts here.
    @State private var axisPresentation = DSAxisPresentation()

    var body: some Scene {
        WindowGroup {
            DSShowcaseRoot(presentation: axisPresentation)
        }
        #if os(macOS)
        .defaultSize(width: 1280, height: 880)
        .commands {
            DSShowcaseCommands(presentation: axisPresentation)
        }
        #endif
    }
}
