// `tokens/export/README.md` (ARCHITECTURE §9.0, §9.9, §9.10; ADR-0024 §11.2): generated, like every
// file under `tokens/export/`. It says what the folder is, how each flavor encodes names and values,
// and which tokens each flavor omits (Tokens Studio has no duration, cubicBezier or transition type
// and no object-form stroke style; Figma variables hold no composite), so a designer sees the gaps.
// ARCHITECTURE §3.1 names this renderer `formats/export-readme.ts`; the format registry has no such
// target, so the Tokens Studio format emits the file.
import { BRAND_MODIFIER, COLOR_SCHEME_MODIFIER, PATHS, PLATFORM_MODIFIER, WEB_PLATFORM } from '../../config.ts';
import { compareIds } from '../../ir/order.ts';
import type { SourceModel } from '../../source/types.ts';
import { BUILD_COMMAND } from '../header.ts';
import type { FigmaFile } from '../figma/variables.ts';
import type { StudioSet, StudioTheme } from './sets.ts';

export const EXPORT_README_PATH = `${PATHS.export}/README.md`;

function code(s: string): string {
  return `\`${s}\``;
}

function list(items: readonly string[]): string {
  if (items.length <= 1) return items.join('');
  return `${items.slice(0, -1).join(', ')} and ${items[items.length - 1] ?? ''}`;
}

/** `type: id, id` per type, in first-seen type order, ids in canonical order and each once. */
function byType(items: readonly { readonly id: string; readonly type: string }[]): string[] {
  const groups = new Map<string, Set<string>>();
  for (const i of items) {
    const g = groups.get(i.type) ?? new Set<string>();
    g.add(i.id);
    groups.set(i.type, g);
  }
  return [...groups].map(([type, ids]) => `${type}: ${[...ids].sort(compareIds).map(code).join(', ')}`);
}

export interface ExportReadmeInput {
  readonly model: SourceModel;
  readonly sets: readonly StudioSet[];
  readonly themes: readonly StudioTheme[];
  readonly figma: readonly FigmaFile[];
}

export function exportReadme(input: ExportReadmeInput): string {
  const { model, sets, themes, figma } = input;
  const groups = new Map<string, number>();
  for (const t of themes) groups.set(t.group, (groups.get(t.group) ?? 0) + 1);
  const anchor = themes[0]?.group ?? null;
  const others = model.modifiers.filter((m) => !groups.has(m.name));
  const figmaVars = [...new Set(figma.map((f) => f.variables.length))];
  const omittedFigma = figma.flatMap((f) => f.omitted.map((o) => ({ id: o.id, type: o.type })));
  const atDefault = model.modifiers
    .filter((m) => m.name !== BRAND_MODIFIER && m.name !== PLATFORM_MODIFIER && m.name !== COLOR_SCHEME_MODIFIER)
    .map((m) => code(`${m.name}=${m.default}`));
  const lines: string[] = [
    '# tokens/export (generated)',
    '',
    `Generated by tools/tokens from ${code(model.resolverFile)}. Do not edit; run ${BUILD_COMMAND}.`,
    '',
    'This folder holds the design-tool flavors of the token source (ADR-0005, ADR-0024 §11 and §12). It is not a source of truth: change `tokens/` or `brands/` and rebuild. No resolver source may point into it (`source/export-path`), and its files are named `*.json`, never `*.tokens.json`, so the schema glob `tokens/**/*.tokens.json` never reads them.',
    '',
    '## Tokens Studio: `tokens-studio/`',
    '',
    "Tokens Studio's DTCG flavor with string values, laid out for its multi-file Git sync.",
    '',
    `- **Sets.** ${sets.length} token sets mirror the resolver's source documents one to one, aliases kept. A set is named by its document's path under \`tokens/\` without \`.tokens.json\`, and \`brands/<name>\` for a brand file.`,
    '- **Names.** Public paths as nested groups: `sys.` dropped, `ref.` and `comp.` kept, `$root` written as `default`. Alias strings are rewritten to match (`{sys.color.bg.surface.$root}` becomes `{color.bg.surface.default}`).',
    `- **Themes** (\`$themes.json\`). One grouped theme per context of ${list([...groups].map(([g, n]) => `${code(g)} (${n})`))}.${anchor === null ? '' : ` A ${code(anchor)} theme also enables the invariant sets${others.length === 0 ? '' : ` and the default contexts of ${list(others.map((m) => `${code(m.name)} (${code(m.default)})`))}`}, so one theme per group resolves every alias.`} A context layered from two documents enables both.`,
    '- **Order** (`$metadata.json`). `tokenSetOrder` is the resolution order flattened, each set at its first occurrence; a later set overrides an earlier one.',
    '- **Values.** Colors are `#rrggbb`, or `rgba(R, G, B, A)` below alpha 1, never 8-digit hex, which Tokens Studio reads as ARGB. A tint (an alias with `app.prism.alpha`) stays an alias and carries `$extensions["studio.tokens"].modify` of type `alpha`, so a brand theme re-colors it. Dimensions are strings such as `24px`, typed `spacing` (`space.*`), `sizing` (`size.*`), `borderRadius` (`radius.*`) or `dimension`; `opacity.*` numbers are `opacity`, flags `boolean`, other numbers `number`; font families are `fontFamilies` (the stack joined), font weights `fontWeights`, typography an object of strings, shadows `boxShadow` and gradients a `color` holding a `linear-gradient(…)` string. A component token takes the type of its alias target. The flavor carries no code syntax (ADR-0026).',
    '- **Typography** shows the authored values. The brand type scale (`ref.type.scale`) and the derived dark and Increase Contrast weights (ADR-0021 §4) are applied in the Figma-native flavor only.',
    '- **Paid plan.** Grouped (multi-mode) themes and color modifiers (the tints) need Tokens Studio\'s paid plan.',
    '',
  ];
  const studioOmitted = sets.filter((s) => s.omitted.length > 0);
  if (studioOmitted.length > 0) {
    lines.push(
      'Omitted, because Tokens Studio has no duration, cubicBezier or transition type and takes stroke styles as keywords only:',
      '',
      '| Set | Omitted tokens |',
      '|-----|----------------|',
      ...studioOmitted.map((s) => `| ${code(s.name)} | ${byType(s.omitted).join('; ')} |`),
      '',
    );
  }
  lines.push(
    '## Figma-native: `figma/`',
    '',
    `- **Files.** One file per brand and color scheme, each imported as one mode: ${list(figma.map((f) => code(f.mode.path.slice(`${PATHS.export}/`.length))))}. Values are resolved at \`${PLATFORM_MODIFIER}=${WEB_PLATFORM}\` with every other modifier at its default${atDefault.length === 0 ? '' : ` (${list(atDefault)})`}.`,
    `- **Variables.** \`sys\` and \`comp\` tokens only (${list(figmaVars.map(String))} variables per file), named by public path as nested groups (\`$root\` → \`default\`). Values only, no aliases: cross-file aliases need \`com.figma.aliasData\` variable ids (a follow-up).`,
    '- **Types.** Colors are sRGB objects: the gamut-mapped components (4 decimals), the authored `alpha` (3 decimals) and a 6-digit `hex` of the same color without alpha, so a translucent color keeps its alpha (ADR-0024 §12); dimensions `{ value, unit: "px" }`; durations `{ value, unit: "s" }`; a font family is the first family of the web stack; numbers; flags are numbers with `com.figma.type: "boolean"`. Typography splits into `font-family`, `font-size`, `font-weight`, `line-height` and `letter-spacing` with the derived weights of the file\'s color scheme; a spring splits into its Apple `duration` and `bounce`.',
    '- **Code syntax** (ADR-0026). Every variable carries `$extensions["com.figma.codeSyntax"]` with `WEB`, the CSS custom property (`var(--ds-color-bg-surface)`), and `iOS`, the member path on the Swift token set (`tokens.color.bgSurface`), both derived from the build\'s naming rules. Authored `figma.scopes` become `com.figma.scopes`.',
    '- **Code syntax names the member that carries a primitive, not always in the variable\'s unit.** A typography `letter-spacing` variable is in px at the role\'s size, while `WEB` and `iOS` name the em members (`var(--ds-type-body-md-letter-spacing)`, `tokens.typography.bodyMd.trackingEm`): px = em × font size. The web has no property that holds a spring\'s Apple `duration` or `bounce`, so both halves name the transition shorthand on `WEB` (`var(--ds-motion-spring-snappy)`, the settle duration and its `linear()` curve) and the `DSSpringToken` field on `iOS`.',
    '',
  );
  if (omittedFigma.length > 0) {
    lines.push(
      'Omitted, because Figma variables hold only colors, numbers, strings and booleans:',
      '',
      ...byType(omittedFigma).map((line) => `- ${line}`),
      '',
    );
  }
  lines.push(
    '## Pending manual checks',
    '',
    '- ARCHITECTURE V3: one Tokens Studio import (paid plan) confirms `$root` as `default`, `tokenSetOrder`, grouped themes, `rgba()` colors and the alpha modifier on aliases.',
    '- ARCHITECTURE V4: one Figma import per mode confirms that a translucent variable keeps its alpha and which `$extensions` key carries code syntax, and whether a letter-spacing variable can hold em, so that it and its code syntax share a unit.',
  );
  return `${lines.join('\n')}\n`;
}
