// Static generated-file headers (ARCHITECTURE §9, §12 rule 4): no timestamps, versions, paths of
// the machine or anything else that changes between runs.

export const BUILD_COMMAND = '`pnpm tokens:build`';

/** `/* … *\/` header of a per-brand CSS file. */
export function cssHeader(resolver: string, what: string): string {
  return `/* Generated by tools/tokens from ${resolver} (${what}). Do not edit; run ${BUILD_COMMAND}. */`;
}

/** `// …` header of a generated TypeScript file. */
export function tsHeader(source: string, what: string | null): string {
  return `// Generated by tools/tokens from ${source}${what === null ? '' : ` (${what})`}. Do not edit; run ${BUILD_COMMAND}.`;
}

/** The `$generated` marker of a generated JSON file. */
export function jsonMarker(resolver: string): string {
  return `tools/tokens from ${resolver}; do not edit`;
}
