// `prism/tailwind-theme`: `tailwind.css` (ARCHITECTURE §9.4; ADR-0019 §3). Brand-invariant and
// `sys.*` only: the five root-level `ds-*` variants (an attribute form and a media form each, from
// WEB_RUNTIME), `@theme inline` variables in Tailwind 4's per-utility namespaces (`bg-ds-page`,
// `text-ds-primary`) that reference the CSS variables, and one `@utility type-ds-<role>` per type
// role. The collision check maps every theme variable through Tailwind 4.3.3's families
// (config.TAILWIND_FAMILIES) and fails when two could produce the same utility name.
import { TAILWIND_FAMILIES, TAILWIND_TYPE_UTILITY, TAILWIND_VARIANTS, WEB_OUTPUT_ROOT, WEB_RUNTIME } from '../config.ts';
import { error, type Diagnostic } from '../ir/diagnostics.ts';
import { cssName, tailwindThemeNames, tailwindTypeUtility } from '../ir/naming.ts';
import { compareIds } from '../ir/order.ts';
import type { IRBundle } from '../ir/types.ts';
import { cssModel } from './css/model.ts';
import { attr, isWebToken, mediaFor, notValid, tokenAt, webScopes, type WebScope } from './css/web.ts';
import type { FormatInput, FormatOutput } from './index.ts';

export const TAILWIND_CSS_PATH = `${WEB_OUTPUT_ROOT}/tailwind.css`;

export const TAILWIND_HEADER = '/* Generated by tools/tokens. Import after "tailwindcss", then one Prism <brand>/tokens.css and motion.css. Do not edit; run `pnpm tokens:build`. */';

export interface ThemeVariable {
  readonly variable: string;
  readonly namespace: string;
  readonly name: string;
  readonly subKey: string | null;
  readonly value: string;
  readonly tokenId: string;
}

export interface TypeUtility {
  readonly name: string;
  readonly tokenId: string;
  readonly properties: readonly (readonly [string, string])[];
}

export interface TailwindModel {
  readonly variants: readonly { readonly name: string; readonly body: string }[];
  readonly theme: readonly ThemeVariable[];
  readonly utilities: readonly TypeUtility[];
}

/** One `@custom-variant` block: the attribute form, then the media form with the valid-value `:not()` list. */
export function variantBody(name: string, axis: string, value: string): string {
  const r = WEB_RUNTIME[axis];
  if (r === undefined) throw new Error(`TAILWIND_VARIANTS names an unknown axis ${axis}`);
  const on = `:root${attr(r, value)}`;
  const lines = [`@custom-variant ${name} {`, `  &:where(${on}, ${on} *) { @slot; }`];
  const media = mediaFor(r, value);
  if (media !== null) {
    const fallback = `:root${notValid(r)}`;
    lines.push(`  @media ${media} {`, `    &:where(${fallback}, ${fallback} *) { @slot; }`, '  }');
  }
  lines.push('}');
  return lines.join('\n');
}

export function tailwindModel(scope: WebScope): TailwindModel {
  const perm = scope.perms[scope.defaultIndex];
  const theme: ThemeVariable[] = [];
  const utilities: TypeUtility[] = [];
  for (const id of [...scope.ids].sort(compareIds)) {
    if (perm === undefined || !isWebToken(id) || !id.startsWith('sys.')) continue;
    const t = tokenAt(perm, id);
    for (const n of tailwindThemeNames(id, t.type)) {
      theme.push({ variable: n.variable, namespace: n.namespace, name: n.name, subKey: n.subKey, value: `var(${n.references})`, tokenId: id });
    }
    const u = tailwindTypeUtility(id, t.type);
    if (u !== null) {
      utilities.push({ name: u, tokenId: id, properties: TAILWIND_TYPE_UTILITY.properties.map(([property, suffix]) => [property, `var(${cssName(id)}${suffix})`] as const) });
    }
  }
  theme.sort((a, b) => (a.variable < b.variable ? -1 : a.variable > b.variable ? 1 : 0));
  return { variants: TAILWIND_VARIANTS.map((v) => ({ name: v.name, body: variantBody(v.name, v.axis, v.value) })), theme, utilities };
}

export function renderTailwindText(model: TailwindModel): string {
  const lines = [TAILWIND_HEADER];
  for (const v of model.variants) lines.push(v.body);
  lines.push('@theme inline {');
  for (const t of model.theme) lines.push(`  ${t.variable}: ${t.value};`);
  lines.push('}');
  for (const u of model.utilities) {
    lines.push(`@utility ${u.name} {`, ...u.properties.map(([p, v]) => `  ${p}: ${v};`), '}');
  }
  return `${lines.join('\n')}\n`;
}

/**
 * Two theme variables, or a theme variable and a static utility, that can produce the same utility
 * name: an error naming both tokens, even where Tailwind's lookup order would pick one silently.
 */
export function tailwindCollisions(theme: readonly Pick<ThemeVariable, 'variable' | 'namespace' | 'name' | 'subKey' | 'tokenId'>[], utilities: readonly Pick<TypeUtility, 'name' | 'tokenId'>[]): Diagnostic[] {
  const out: Diagnostic[] = [];
  const byUtility = new Map<string, { variable: string; tokenId: string }[]>();
  const add = (utility: string, source: { variable: string; tokenId: string }): void => {
    const list = byUtility.get(utility) ?? [];
    if (!list.some((s) => s.variable === source.variable)) list.push(source);
    byUtility.set(utility, list);
  };
  const variables = new Map<string, string>();
  for (const t of theme) {
    const prev = variables.get(t.variable);
    if (prev !== undefined && prev !== t.tokenId) out.push(error('tailwind/collision', `${prev} and ${t.tokenId} both define the theme variable ${t.variable}`, { tokenId: t.tokenId }));
    variables.set(t.variable, t.tokenId);
    if (t.subKey !== null) continue;
    const families = TAILWIND_FAMILIES[t.namespace];
    if (families === undefined) {
      out.push(error('tailwind/namespace', `${t.variable} (${t.tokenId}) uses the namespace ${t.namespace}, which config.TAILWIND_FAMILIES does not list; the collision check cannot cover it`, { tokenId: t.tokenId, hint: 'add the namespace with the families Tailwind derives from it' }));
      continue;
    }
    for (const f of families) add(`${f}-ds-${t.name}`, { variable: t.variable, tokenId: t.tokenId });
  }
  for (const u of utilities) add(u.name, { variable: `@utility ${u.name}`, tokenId: u.tokenId });
  for (const [utility, sources] of [...byUtility].sort((a, b) => (a[0] < b[0] ? -1 : 1))) {
    if (sources.length < 2) continue;
    const names = sources.map((s) => `${s.variable} (${s.tokenId})`).join(' and ');
    out.push(error('tailwind/collision', `the utility ${utility} can come from ${names}; Tailwind would pick one silently (ARCHITECTURE §9.4)`, { tokenId: sources[1]?.tokenId ?? '', hint: 'rename one of the tokens, or change its namespace in config.TAILWIND_THEME' }));
  }
  return out;
}

function referencedVariables(text: string): string[] {
  return [...text.matchAll(/var\((--ds-[a-z0-9-]+)\)/g)].map((m) => m[1] ?? '');
}

export function checkTailwind(bundle: IRBundle): { text: string | null; diagnostics: Diagnostic[] } {
  const diagnostics: Diagnostic[] = [];
  const scopes = webScopes(bundle);
  const texts = scopes.map((scope) => {
    const model = tailwindModel(scope);
    const text = renderTailwindText(model);
    const declared = new Set(cssModel(scope).specs.map((s) => s.name));
    for (const v of new Set(referencedVariables(text))) {
      if (!declared.has(v)) diagnostics.push(error('tailwind/unknown-var', `tailwind.css references ${v}, which ${scope.brand}/tokens.css and motion.css do not declare`, {}));
    }
    if (scope === scopes[0]) diagnostics.push(...tailwindCollisions(model.theme, model.utilities));
    return { brand: scope.brand, text };
  });
  const [first] = texts;
  for (const t of texts) {
    if (first !== undefined && t.text !== first.text) diagnostics.push(error('format/brand-variant', `tailwind.css differs between brand "${first.brand}" and brand "${t.brand}"; Tailwind names are brand-invariant (ARCHITECTURE §9.4)`));
  }
  return { text: first?.text ?? null, diagnostics };
}

export function renderTailwindTheme(input: FormatInput): FormatOutput {
  const { text, diagnostics } = checkTailwind(input.bundle);
  return { files: text === null ? [] : [{ path: TAILWIND_CSS_PATH, contents: text }], diagnostics };
}
