// The four generated artifacts of the icon registry (roadmap P2-2, ADR-0013 decision 5):
//
//   web/packages/react/src/generated/icons.ts            `iconRegistry` and its tables (ADR-0019 §6, G-20)
//   swift/Sources/DSIcons/Generated/DSIconName.swift     `DSIconName` and the weight, style and size tables
//   swift/Sources/DSIcons/Resources/Icons.xcassets/…     the Phosphor-derived image sets (critic G-09)
//   spec/icons/generated/tokens-studio/…                 the icon list for Tokens Studio
//
// Every renderer is a pure function of the registry (plus the Phosphor SVG bytes for the catalog), so
// the output is byte-identical across runs and `icons:validate` can compare it with the committed
// files. Ids are emitted in sorted order, never in document order.

import { assetName, mirrorOf, PHOSPHOR_CUTS, SIZE_NAMES, STYLE_NAMES, WEIGHT_NAMES, type Icon, type Registry } from "./registry.ts";
import { assetFile, readAsset, readLicense, type Catalog } from "./phosphor.ts";
import { requiredCuts } from "./checks.ts";

/** One generated file: a repository-relative POSIX path inside `OWNED_ROOTS` and its bytes. */
export interface OutputFile {
  readonly path: string;
  readonly contents: string;
}

const WEB_PATH = "web/packages/react/src/generated/icons.ts";
const SWIFT_PATH = "swift/Sources/DSIcons/Generated/DSIconName.swift";
const XCASSETS_ROOT = "swift/Sources/DSIcons/Resources/Icons.xcassets";
const LICENSE_PATH = "swift/Sources/DSIcons/Resources/Phosphor-LICENSE.txt";
const TOKENS_STUDIO_ROOT = "spec/icons/generated/tokens-studio";

const BUILD_COMMAND = "pnpm icons:build";

function sortedIds(registry: Registry): readonly string[] {
  return Object.keys(registry.icons).sort();
}

/** `nav.back` -> `navBack`, `action.zoom-in` -> `actionZoomIn`. */
export function swiftCase(id: string): string {
  const parts = id.split(/[.-]/);
  return parts.map((part, index) => (index === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1))).join("");
}

/** `caret-left` -> `CaretLeftIcon`, the export name of `@phosphor-icons/react`. */
export function reactComponent(pascalName: string): string {
  return `${pascalName}Icon`;
}

function quote(value: string): string {
  return JSON.stringify(value);
}

function json(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

// ---- web ---------------------------------------------------------------------------------------

/**
 * `iconRegistry` for `@iiiivaska/prism-react` (ADR-0019 §6: the map is `iconRegistry`, the component
 * is `Icon`). It carries the web binding only: no Apple field ever reaches the web package, because
 * SF Symbols are licensed for Apple user interfaces alone (ADR-0013 rule 5).
 */
export function renderWebRegistry(registry: Registry, catalog: Catalog): OutputFile {
  const lines: string[] = [];
  lines.push(`// Generated by tools/icons from spec/icons/registry.json. Do not edit; run \`${BUILD_COMMAND}\`.`);
  lines.push("//");
  lines.push("// The web half of the registry: Phosphor names and the metadata `Icon` needs (ADR-0013, ADR-0019 §6).");
  lines.push("// It holds no SF Symbol name by construction (ADR-0013 rule 5).");
  lines.push("");
  lines.push(`/** The registry version, equal to the system version. */`);
  lines.push(`export const iconRegistryVersion = ${quote(registry.version)};`);
  lines.push("");
  lines.push(`/** The icon set every web binding comes from (ADR-0013 decision 2). */`);
  lines.push(`export const iconSource = { package: ${quote(registry.sources.phosphor.package)}, version: ${quote(registry.sources.phosphor.version)} } as const;`);
  lines.push("");
  lines.push(`export type IconName =\n${sortedIds(registry)
    .map((id) => `  | ${quote(id)}`)
    .join("\n")};`);
  lines.push("");
  lines.push(`export type IconWeight = ${WEIGHT_NAMES.map(quote).join(" | ")};`);
  lines.push(`export type IconStyle = ${STYLE_NAMES.map(quote).join(" | ")};`);
  lines.push(`export type IconSize = ${SIZE_NAMES.map(quote).join(" | ")};`);
  lines.push(`export type PhosphorCut = ${PHOSPHOR_CUTS.map(quote).join(" | ")};`);
  lines.push("");
  lines.push("export interface IconEntry {");
  lines.push("  /** The Phosphor name to render. */");
  lines.push("  readonly phosphor: string;");
  lines.push("  /** The `@phosphor-icons/react` export that draws it. */");
  lines.push("  readonly component: string;");
  lines.push("  /** i18n key of the accessibility label. */");
  lines.push("  readonly label: string;");
  lines.push("  readonly categories: readonly string[];");
  lines.push("  /** Search terms; an agent looks an icon up by tag or category, never by vendor name. */");
  lines.push("  readonly tags: readonly string[];");
  lines.push("  /** Flip the glyph under `dir=\"rtl\"`. */");
  lines.push("  readonly rtlMirror: boolean;");
  lines.push("  readonly defaultStyle: IconStyle;");
  lines.push("  readonly since: string;");
  lines.push("  readonly deprecated?: { readonly since: string; readonly replacedBy: IconName };");
  lines.push("}");
  lines.push("");
  lines.push("/** Every weight token: the Phosphor cut it renders and the number a numeric token carries. */");
  lines.push("export const iconWeights: Readonly<Record<IconWeight, { readonly phosphor: PhosphorCut; readonly number: number; readonly boldText: IconWeight }>> = {");
  for (const name of WEIGHT_NAMES) {
    const weight = registry.weights[name];
    lines.push(`  ${name}: { phosphor: ${quote(weight.phosphor)}, number: ${weight.number}, boldText: ${quote(weight.boldText)} },`);
  }
  lines.push("};");
  lines.push("");
  lines.push('/** Every style token: the Phosphor cut it renders, or `null` when it renders the weight cut. */');
  lines.push("export const iconStyles: Readonly<Record<IconStyle, PhosphorCut | null>> = {");
  for (const name of STYLE_NAMES) {
    const style = registry.styles[name];
    lines.push(`  ${name}: ${style.phosphor === "$weight" ? "null" : quote(style.phosphor)},`);
  }
  lines.push("};");
  lines.push("");
  lines.push("/** The px icon boxes of `ref.size.icon`. */");
  lines.push("export const iconSizes: Readonly<Record<IconSize, number>> = {");
  for (const name of SIZE_NAMES) lines.push(`  ${name}: ${registry.sizes[name].px},`);
  lines.push("};");
  lines.push("");
  lines.push("export const iconRegistry: Readonly<Record<IconName, IconEntry>> = {");
  for (const id of sortedIds(registry)) {
    const icon = registry.icons[id] as Icon;
    const entry = catalog.byName.get(icon.web.phosphor);
    const fields = [
      `phosphor: ${quote(icon.web.phosphor)}`,
      `component: ${quote(reactComponent(entry?.pascalName ?? icon.web.phosphor))}`,
      `label: ${quote(icon.label)}`,
      `categories: [${icon.categories.map(quote).join(", ")}]`,
      `tags: [${icon.tags.map(quote).join(", ")}]`,
      `rtlMirror: ${mirrorOf(icon).web}`,
      `defaultStyle: ${quote(icon.defaultStyle ?? "outline")}`,
      `since: ${quote(icon.since)}`,
    ];
    if (icon.deprecated) fields.push(`deprecated: { since: ${quote(icon.deprecated.since)}, replacedBy: ${quote(icon.deprecated.replacedBy)} }`);
    lines.push(`  ${quote(id)}: { ${fields.join(", ")} },`);
  }
  lines.push("};");
  lines.push("");
  return { path: WEB_PATH, contents: lines.join("\n") };
}

// ---- Swift -------------------------------------------------------------------------------------

function swiftDoc(indent: string, text: string): string {
  return `${indent}/// ${text}`;
}

/**
 * `DSIconName` and the tables the Phase 3 `DSIcon` view resolves through (ADR-0019 §6). The enum
 * carries both Apple bindings: an SF Symbol name, or the image-set stem of a Phosphor-derived set in
 * `Icons.xcassets` (critic G-09).
 */
export function renderSwiftEnum(registry: Registry): OutputFile {
  const ids = sortedIds(registry);
  const lines: string[] = [];
  const floor = registry.sources.sfSymbols.osFloor;
  lines.push(`// Generated by tools/icons from spec/icons/registry.json. Do not edit; run \`${BUILD_COMMAND}\`.`);
  lines.push("import SwiftUI");
  lines.push("");
  lines.push("/// Every icon of the registry, by semantic id (ADR-0013 decision 1). The SwiftUI view that draws one is");
  lines.push("/// `DSIcon` (ADR-0019 §6, Phase 3); nothing outside this file spells an SF Symbol name (ADR-0013 rule 1).");
  lines.push("public enum DSIconName: String, CaseIterable, Hashable, Sendable {");
  for (const id of ids) {
    const icon = registry.icons[id] as Icon;
    lines.push(swiftDoc("    ", `${icon.label} — ${icon.tags.join(", ")}`));
    lines.push(`    case ${swiftCase(id)} = ${quote(id)}`);
  }
  lines.push("");
  lines.push(`    /// The registry version, equal to the system version.`);
  lines.push(`    public static let registryVersion = ${quote(registry.version)}`);
  lines.push("");
  lines.push(`    /// The SF Symbol this icon renders, or nil when it renders a Phosphor image set from \`Icons.xcassets\`.`);
  lines.push(`    /// Every name here is available at iOS, macOS and watchOS ${floor} (tools/icons-apple).`);
  lines.push("    public var symbol: String? {");
  lines.push("        switch self {");
  for (const id of ids) {
    const icon = registry.icons[id] as Icon;
    lines.push(`        case .${swiftCase(id)}: ${icon.apple.symbol === undefined ? "nil" : quote(icon.apple.symbol)}`);
  }
  lines.push("        }");
  lines.push("    }");
  lines.push("");
  lines.push(`    /// The image-set stem in \`Icons.xcassets\` for an icon Prism draws from Phosphor, or nil for an SF Symbol.`);
  lines.push(`    /// One image set per cut: \`"\\(asset).\\(weight.phosphorCut)"\` (critic G-09).`);
  lines.push("    public var asset: String? {");
  lines.push("        switch self {");
  for (const id of ids) {
    const icon = registry.icons[id] as Icon;
    lines.push(`        case .${swiftCase(id)}: ${icon.apple.custom === undefined ? "nil" : quote(icon.apple.custom)}`);
  }
  lines.push("        }");
  lines.push("    }");
  lines.push("");
  lines.push("    /// i18n key of the accessibility label.");
  lines.push("    public var label: String { \"icon.\\(rawValue)\" }");
  lines.push("");
  lines.push("    /// Flip the glyph in a right-to-left layout. False for a symbol the system already mirrors (critic C-24).");
  lines.push("    public var mirrorsInRTL: Bool {");
  lines.push("        switch self {");
  const mirrored = ids.filter((id) => mirrorOf(registry.icons[id] as Icon).apple);
  if (mirrored.length > 0) {
    lines.push(`        case ${mirrored.map((id) => `.${swiftCase(id)}`).join(", ")}: true`);
    lines.push("        default: false");
  } else {
    lines.push("        default: false");
  }
  lines.push("        }");
  lines.push("    }");
  lines.push("");
  lines.push("    /// The style the icon renders when the caller names none.");
  lines.push("    public var defaultStyle: DSIconStyle {");
  lines.push("        switch self {");
  for (const style of STYLE_NAMES) {
    const members = ids.filter((id) => ((registry.icons[id] as Icon).defaultStyle ?? "outline") === style);
    if (members.length === 0) continue;
    if (style === "outline") continue;
    lines.push(`        case ${members.map((id) => `.${swiftCase(id)}`).join(", ")}: .${style}`);
  }
  lines.push("        default: .outline");
  lines.push("        }");
  lines.push("    }");
  lines.push("");
  lines.push("    /// Tags and categories an agent searches by (critic C-22): the registry is the only lookup.");
  lines.push("    public var tags: [String] {");
  lines.push("        switch self {");
  for (const id of ids) {
    const icon = registry.icons[id] as Icon;
    lines.push(`        case .${swiftCase(id)}: [${[...icon.categories, ...icon.tags].map(quote).join(", ")}]`);
  }
  lines.push("        }");
  lines.push("    }");
  lines.push("}");
  lines.push("");
  lines.push("/// The icon weight token (ADR-0013 decision 4). `number` is the value a numeric weight token carries,");
  lines.push("/// so `DSTokenSet.Icon.weight` resolves to a case through `init(number:)` (critic C-23).");
  lines.push("public enum DSIconWeight: String, CaseIterable, Hashable, Sendable {");
  for (const name of WEIGHT_NAMES) lines.push(`    case ${name}`);
  lines.push("");
  lines.push("    public var number: Int {");
  lines.push("        switch self {");
  for (const name of WEIGHT_NAMES) lines.push(`        case .${name}: ${registry.weights[name].number}`);
  lines.push("        }");
  lines.push("    }");
  lines.push("");
  lines.push("    /// The San Francisco weight an SF Symbol renders at.");
  lines.push("    public var fontWeight: Font.Weight {");
  lines.push("        switch self {");
  for (const name of WEIGHT_NAMES) lines.push(`        case .${name}: .${swiftFontWeight(registry.weights[name].sf)}`);
  lines.push("        }");
  lines.push("    }");
  lines.push("");
  lines.push("    /// The Phosphor cut an image set renders (the four drawn cuts; Phosphor has no medium).");
  lines.push("    public var phosphorCut: String {");
  lines.push("        switch self {");
  for (const name of WEIGHT_NAMES) lines.push(`        case .${name}: ${quote(registry.weights[name].phosphor)}`);
  lines.push("        }");
  lines.push("    }");
  lines.push("");
  lines.push("    /// The weight this one steps to under Bold Text on iOS, iPadOS and watchOS (ADR-0021 §3);");
  lines.push("    /// macOS and the web have no such setting. The web saturates at the bold cut, which Phosphor's four cuts impose.");
  lines.push("    public var boldText: DSIconWeight {");
  lines.push("        switch self {");
  for (const name of WEIGHT_NAMES) lines.push(`        case .${name}: .${registry.weights[name].boldText}`);
  lines.push("        }");
  lines.push("    }");
  lines.push("");
  lines.push("    /// The weight a numeric token such as `DSTokenSet.Icon.weight` names, or nil when no weight carries it.");
  lines.push("    public init?(number: Int) {");
  lines.push("        switch number {");
  for (const name of WEIGHT_NAMES) lines.push(`        case ${registry.weights[name].number}: self = .${name}`);
  lines.push("        default: return nil");
  lines.push("        }");
  lines.push("    }");
  lines.push("}");
  lines.push("");
  lines.push("/// The icon style token (ADR-0013 decision 4): the SF variant or rendering mode, and the Phosphor cut.");
  lines.push("public enum DSIconStyle: String, CaseIterable, Hashable, Sendable {");
  for (const name of STYLE_NAMES) lines.push(`    case ${name}`);
  lines.push("");
  lines.push("    /// The `.symbolVariant` an SF Symbol takes, or nil when the style keeps the plain variant.");
  lines.push("    public var symbolVariant: SymbolVariants? {");
  lines.push("        switch self {");
  for (const name of STYLE_NAMES) {
    const variant = registry.styles[name].sf.variant;
    lines.push(`        case .${name}: ${variant === undefined || variant === "none" ? "nil" : `.${swiftSymbolVariant(variant)}`}`);
  }
  lines.push("        }");
  lines.push("    }");
  lines.push("");
  lines.push("    /// The `.symbolRenderingMode` the style asks for, or nil for the inherited mode.");
  lines.push("    public var renderingMode: SymbolRenderingMode? {");
  lines.push("        switch self {");
  for (const name of STYLE_NAMES) {
    const mode = registry.styles[name].sf.renderingMode;
    lines.push(`        case .${name}: ${mode === undefined ? "nil" : `.${mode}`}`);
  }
  lines.push("        }");
  lines.push("    }");
  lines.push("");
  lines.push("    /// The Phosphor cut an image set renders, or nil when the style renders the weight cut.");
  lines.push("    public var phosphorCut: String? {");
  lines.push("        switch self {");
  for (const name of STYLE_NAMES) {
    const cut = registry.styles[name].phosphor;
    lines.push(`        case .${name}: ${cut === "$weight" ? "nil" : quote(cut)}`);
  }
  lines.push("        }");
  lines.push("    }");
  lines.push("}");
  lines.push("");
  lines.push("/// The px icon boxes of `ref.size.icon` and the SF point size measured to fill each one at the Large");
  lines.push("/// content size (critic C-23). Dynamic Type scales both sides from there.");
  lines.push("public enum DSIconSize: String, CaseIterable, Hashable, Sendable {");
  for (const name of SIZE_NAMES) lines.push(`    case ${name}`);
  lines.push("");
  lines.push("    /// The box the icon is laid out in, in points.");
  lines.push("    public var box: CGFloat {");
  lines.push("        switch self {");
  for (const name of SIZE_NAMES) lines.push(`        case .${name}: ${registry.sizes[name].px}`);
  lines.push("        }");
  lines.push("    }");
  lines.push("");
  lines.push("    /// The SF Symbol point size that fills the box.");
  lines.push("    public var pointSize: CGFloat {");
  lines.push("        switch self {");
  for (const name of SIZE_NAMES) lines.push(`        case .${name}: ${registry.sizes[name].sf.pointSize}`);
  lines.push("        }");
  lines.push("    }");
  lines.push("");
  lines.push("    /// The SF Symbol scale the measurement was taken at.");
  lines.push("    public var scale: Image.Scale {");
  lines.push("        switch self {");
  for (const name of SIZE_NAMES) lines.push(`        case .${name}: .${registry.sizes[name].sf.scale}`);
  lines.push("        }");
  lines.push("    }");
  lines.push("}");
  lines.push("");
  return { path: SWIFT_PATH, contents: lines.join("\n") };
}

function swiftFontWeight(sf: string): string {
  return sf === "ultralight" ? "ultraLight" : sf;
}

function swiftSymbolVariant(variant: string): string {
  return variant
    .split(".")
    .map((part, index) => (index === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join("");
}

// ---- Apple asset catalog (critic G-09) ---------------------------------------------------------

/**
 * One image set per Phosphor-derived icon and cut, `preserves-vector-representation` on and the
 * template rendering intent set, so the glyph tints with `foregroundStyle` and stays vector at every
 * size. Prism generates the catalog itself instead of depending on `phosphor-icons/swift`, which
 * rasterizes and declares no watchOS (ADR-0013 decision 3).
 */
export function renderXcassets(registry: Registry, catalog: Catalog): { readonly files: readonly OutputFile[]; readonly missing: readonly string[] } {
  const files: OutputFile[] = [{ path: `${XCASSETS_ROOT}/Contents.json`, contents: json({ info: { author: "xcode", version: 1 } }) }];
  const missing: string[] = [];
  const cuts = requiredCuts(registry);
  for (const id of sortedIds(registry)) {
    const icon = registry.icons[id] as Icon;
    const custom = icon.apple.custom;
    if (custom === undefined) continue;
    for (const cut of cuts) {
      const svg = readAsset(catalog, icon.web.phosphor, cut);
      if (svg === null) {
        missing.push(`${icon.web.phosphor} (${cut})`);
        continue;
      }
      const file = assetFile(icon.web.phosphor, cut);
      const set = `${XCASSETS_ROOT}/${assetName(custom, cut)}.imageset`;
      files.push({ path: `${set}/${file}`, contents: `${svg}\n` });
      files.push({
        path: `${set}/Contents.json`,
        contents: json({
          images: [{ filename: file, idiom: "universal" }],
          info: { author: "xcode", version: 1 },
          properties: { "preserves-vector-representation": true, "template-rendering-intent": "template" },
        }),
      });
    }
  }
  files.push({ path: LICENSE_PATH, contents: licenseNotice(registry) });
  return { files: files.sort((a, b) => (a.path < b.path ? -1 : 1)), missing };
}

function licenseNotice(registry: Registry): string {
  const header = [
    `The image sets in Icons.xcassets are the SVG sources of ${registry.sources.phosphor.package} ${registry.sources.phosphor.version},`,
    "copied byte for byte by `pnpm icons:build` (tools/icons). They are redistributed under the licence below,",
    "which is the LICENSE file of the installed package. Prism records the item in licenses/inventory.json.",
    "",
    "",
  ].join("\n");
  return header + readLicense().replace(/\r\n/g, "\n").trimEnd() + "\n";
}

// ---- Tokens Studio ------------------------------------------------------------------------------

/**
 * The icon list for Tokens Studio: one `other` token per id holding the Phosphor name, in a set of its
 * own so the design-tool sync can enable it next to `tokens/export/tokens-studio`. It carries no SF
 * Symbol name (ADR-0013 rule 5).
 */
export function renderTokensStudio(registry: Registry): readonly OutputFile[] {
  const icons: Record<string, unknown> = {};
  for (const id of sortedIds(registry)) {
    const icon = registry.icons[id] as Icon;
    const segments = id.split(".");
    let group = icons;
    for (const segment of segments.slice(0, -1)) {
      group[segment] ??= {};
      group = group[segment] as Record<string, unknown>;
    }
    const leaf = segments[segments.length - 1] as string;
    group[leaf] = {
      $type: "other",
      $value: icon.web.phosphor,
      $description: [icon.label, icon.tags.join(", ")].join(" — "),
    };
  }
  return [
    { path: `${TOKENS_STUDIO_ROOT}/$metadata.json`, contents: json({ tokenSetOrder: ["icons"] }) },
    { path: `${TOKENS_STUDIO_ROOT}/icons.json`, contents: json({ icon: icons }) },
  ];
}

/** Every generated file, sorted by path. */
export function renderAll(registry: Registry, catalog: Catalog): { readonly files: readonly OutputFile[]; readonly missing: readonly string[] } {
  const xcassets = renderXcassets(registry, catalog);
  const files = [renderWebRegistry(registry, catalog), renderSwiftEnum(registry), ...xcassets.files, ...renderTokensStudio(registry)];
  return { files: [...files].sort((a, b) => (a.path < b.path ? -1 : 1)), missing: xcassets.missing };
}
