// Generated by scripts/stories.ts from spec/components/Avatar.yaml (specVersion 1). Do not edit;
// run `pnpm --filter @iiiivaska/prism-gallery stories` after the spec changes.
import type { Meta, StoryObj } from "@storybook/react-vite";
import { Avatar } from "@iiiivaska/prism-react";
import { renderAvatarExample, type AvatarExampleArgs, type ExampleFields } from "../harness/examples.tsx";

const meta = {
  title: "Avatar",
  component: Avatar,
  tags: ["vrt"],
  parameters: { prism: { component: "Avatar", specVersion: 1 } },
} satisfies Meta<typeof Avatar>;

export default meta;

type Story = StoryObj<AvatarExampleArgs>;

function example(fields: ExampleFields): Pick<Story, "parameters" | "render"> {
  return { parameters: { prism: { example: fields } }, render: (args) => renderAvatarExample(args, fields) };
}

/** Avatar.yaml example `image-md` */
export const ImageMd: Story = {
  name: "image-md",
  args: {"name":"Anna Petrova","image":{"fixture":"portrait"},"size":"md"},
  ...example({"id":"image-md"}),
};

/** Avatar.yaml example `initials-md`: no image; the circle shows "AP" */
export const InitialsMd: Story = {
  name: "initials-md",
  args: {"name":"Anna Petrova","size":"md"},
  ...example({"id":"initials-md","description":"no image; the circle shows \"AP\""}),
};

/** Avatar.yaml example `initials-one-word`: a one-word name gives one letter */
export const InitialsOneWord: Story = {
  name: "initials-one-word",
  args: {"name":"Northgate","size":"md"},
  ...example({"id":"initials-one-word","description":"a one-word name gives one letter"}),
};

/** Avatar.yaml example `fallback-icon`: neither an image nor a name; the circle shows object.user */
export const FallbackIcon: Story = {
  name: "fallback-icon",
  args: {"size":"md"},
  ...example({"id":"fallback-icon","description":"neither an image nor a name; the circle shows object.user"}),
};

/** Avatar.yaml example `ringed`: the one active avatar in a rail */
export const Ringed: Story = {
  name: "ringed",
  args: {"name":"Anna Petrova","image":{"fixture":"portrait"},"hasRing":true},
  ...example({"id":"ringed","description":"the one active avatar in a rail"}),
};

/** Avatar.yaml example `size-sm` */
export const SizeSm: Story = {
  name: "size-sm",
  args: {"name":"Anna Petrova","size":"sm"},
  ...example({"id":"size-sm"}),
};

/** Avatar.yaml example `size-lg` */
export const SizeLg: Story = {
  name: "size-lg",
  args: {"name":"Anna Petrova","image":{"fixture":"portrait"},"size":"lg"},
  ...example({"id":"size-lg"}),
};

/** Avatar.yaml example `decorative`: the name is written beside the avatar, so the avatar is hidden from assistive technology */
export const Decorative: Story = {
  name: "decorative",
  args: {"name":"Anna Petrova","image":{"fixture":"portrait"},"isDecorative":true},
  ...example({"id":"decorative","description":"the name is written beside the avatar, so the avatar is hidden from assistive technology"}),
};

/** Avatar.yaml example `ringed-over-map`: over media the ring takes color.border.on-glass-fill so it stays visible on the ground */
export const RingedOverMap: Story = {
  name: "ringed-over-map",
  args: {"name":"Anna Petrova","image":{"fixture":"portrait"},"hasRing":true},
  ...example({"id":"ringed-over-map","surface":"map","description":"over media the ring takes color.border.on-glass-fill so it stays visible on the ground"}),
};

/** Avatar.yaml example `initials-over-map`: no portrait covers the circle over media, so the glass chip itself is photographed, with the initials in color.text.on-glass-fill */
export const InitialsOverMap: Story = {
  name: "initials-over-map",
  args: {"name":"Anna Petrova","size":"md"},
  ...example({"id":"initials-over-map","surface":"map","description":"no portrait covers the circle over media, so the glass chip itself is photographed, with the initials in color.text.on-glass-fill"}),
};

/** Avatar.yaml example `on-glass-over-image` */
export const OnGlassOverImage: Story = {
  name: "on-glass-over-image",
  args: {"name":"Anna Petrova","hasRing":true},
  ...example({"id":"on-glass-over-image","surface":"glass","backdrop":"image"}),
};

/** Avatar.yaml example `russian-initials`: the same rule on Cyrillic gives "АП", and the two letters keep the circle's width */
export const RussianInitials: Story = {
  name: "russian-initials",
  args: {"name":"Анна Петрова","size":"md"},
  ...example({"id":"russian-initials","description":"the same rule on Cyrillic gives \"АП\", and the two letters keep the circle's width"}),
};
