// Generated by scripts/stories.ts from spec/components/Badge.yaml (specVersion 1). Do not edit;
// run `pnpm --filter @iiiivaska/prism-gallery stories` after the spec changes.
import type { Meta, StoryObj } from "@storybook/react-vite";
import { Badge } from "@iiiivaska/prism-react";
import { renderBadgeExample, type ExampleFields } from "../harness/examples.tsx";

const meta = {
  title: "Badge",
  component: Badge,
  tags: ["vrt"],
  parameters: { prism: { component: "Badge", specVersion: 1 } },
} satisfies Meta<typeof Badge>;

export default meta;

type Story = StoryObj<typeof meta>;

function example(fields: ExampleFields): Pick<Story, "parameters" | "render"> {
  return { parameters: { prism: { example: fields } }, render: (args) => renderBadgeExample(args, fields) };
}

/** Badge.yaml example `count-neutral` */
export const CountNeutral: Story = {
  name: "count-neutral",
  args: {"variant":"count","tone":"neutral","count":3,"label":"unread alerts"},
  ...example({"id":"count-neutral"}),
};

/** Badge.yaml example `count-critical` */
export const CountCritical: Story = {
  name: "count-critical",
  args: {"variant":"count","tone":"critical","count":12,"label":"open incidents"},
  ...example({"id":"count-critical"}),
};

/** Badge.yaml example `count-accent` */
export const CountAccent: Story = {
  name: "count-accent",
  args: {"variant":"count","tone":"accent","count":7,"label":"items needing attention"},
  ...example({"id":"count-accent"}),
};

/** Badge.yaml example `count-overflow`: renders "99+" in a pill that keeps the count pill's size.icon.md height and capsule shape and widens past a two-digit pill to hug its three characters with space.1 either side */
export const CountOverflow: Story = {
  name: "count-overflow",
  args: {"variant":"count","tone":"critical","count":128,"max":99,"label":"open incidents"},
  ...example({"id":"count-overflow","description":"renders \"99+\" in a pill that keeps the count pill's size.icon.md height and capsule shape and widens past a two-digit pill to hug its three characters with space.1 either side"}),
};

/** Badge.yaml example `outline-neutral`: the resting count beside an active tab's filled badge */
export const OutlineNeutral: Story = {
  name: "outline-neutral",
  args: {"variant":"count","tone":"neutral","emphasis":"outline","count":4,"label":"queued runs"},
  ...example({"id":"outline-neutral","description":"the resting count beside an active tab's filled badge"}),
};

/** Badge.yaml example `outline-critical` */
export const OutlineCritical: Story = {
  name: "outline-critical",
  args: {"variant":"count","tone":"critical","emphasis":"outline","count":2,"label":"open incidents"},
  ...example({"id":"outline-critical"}),
};

/** Badge.yaml example `dot-critical` */
export const DotCritical: Story = {
  name: "dot-critical",
  args: {"variant":"dot","tone":"critical","label":"unread"},
  ...example({"id":"dot-critical"}),
};

/** Badge.yaml example `dot-accent` */
export const DotAccent: Story = {
  name: "dot-accent",
  args: {"variant":"dot","tone":"accent","label":"new"},
  ...example({"id":"dot-accent"}),
};

/** Badge.yaml example `on-vivid`: only the filled emphasis goes over media; its fill is opaque, so the checked pair reaches the digits over the gradient */
export const OnVivid: Story = {
  name: "on-vivid",
  args: {"variant":"count","tone":"neutral","count":3,"label":"unread alerts","emphasis":"filled"},
  ...example({"id":"on-vivid","surface":"vivid","description":"only the filled emphasis goes over media; its fill is opaque, so the checked pair reaches the digits over the gradient"}),
};

/** Badge.yaml example `on-glass-over-map` */
export const OnGlassOverMap: Story = {
  name: "on-glass-over-map",
  tags: ["glass"],
  args: {"variant":"count","tone":"critical","count":2,"label":"open incidents"},
  ...example({"id":"on-glass-over-map","surface":"glass","backdrop":"map"}),
};
