// Generated by scripts/stories.ts from spec/components/Button.yaml (specVersion 5). Do not edit;
// run `pnpm --filter @iiiivaska/prism-gallery stories` after the spec changes.
import type { Meta, StoryObj } from "@storybook/react-vite";
import { fn } from "storybook/test";
import { Button } from "@iiiivaska/prism-react";
import { renderButtonExample, type ExampleFields } from "../harness/examples.tsx";

const meta = {
  title: "Button",
  component: Button,
  tags: ["vrt"],
  args: { onPress: fn() },
  parameters: { prism: { component: "Button", specVersion: 5 } },
} satisfies Meta<typeof Button>;

export default meta;

type Story = StoryObj<typeof meta>;

function example(fields: ExampleFields): Pick<Story, "parameters" | "render"> {
  return { parameters: { prism: { example: fields } }, render: (args) => renderButtonExample(args, fields) };
}

/** Button.yaml example `primary-md` */
export const PrimaryMd: Story = {
  name: "primary-md",
  args: {"variant":"primary","size":"md","label":"Continue"},
  ...example({"id":"primary-md"}),
};

/** Button.yaml example `secondary-md` */
export const SecondaryMd: Story = {
  name: "secondary-md",
  args: {"variant":"secondary","size":"md","label":"Details","trailingIcon":"nav.open"},
  ...example({"id":"secondary-md"}),
};

/** Button.yaml example `ghost-sm` */
export const GhostSm: Story = {
  name: "ghost-sm",
  args: {"variant":"ghost","size":"sm","label":"Filter","leadingIcon":"action.filter"},
  ...example({"id":"ghost-sm"}),
};

/** Button.yaml example `danger-md` */
export const DangerMd: Story = {
  name: "danger-md",
  args: {"variant":"danger","size":"md","label":"Delete route"},
  ...example({"id":"danger-md"}),
};

/** Button.yaml example `loading` */
export const Loading: Story = {
  name: "loading",
  args: {"variant":"primary","size":"md","label":"Saving","isLoading":true},
  ...example({"id":"loading"}),
};

/** Button.yaml example `disabled` */
export const Disabled: Story = {
  name: "disabled",
  args: {"variant":"primary","size":"md","label":"Continue","isDisabled":true},
  ...example({"id":"disabled"}),
};

/** Button.yaml example `on-vivid` */
export const OnVivid: Story = {
  name: "on-vivid",
  args: {"variant":"ghost","size":"md","label":"Open"},
  ...example({"id":"on-vivid","surface":"vivid"}),
};
