// Generated by scripts/stories.ts from spec/components/Card.yaml (specVersion 5). Do not edit;
// run `pnpm --filter @iiiivaska/prism-gallery stories` after the spec changes.
import type { Meta, StoryObj } from "@storybook/react-vite";
import { fn } from "storybook/test";
import { Card } from "@iiiivaska/prism-react";
import { renderCardExample, type ExampleFields } from "../harness/examples.tsx";

const meta = {
  title: "Card",
  component: Card,
  tags: ["vrt"],
  args: { onAction: fn() },
  parameters: { prism: { component: "Card", specVersion: 5 } },
} satisfies Meta<typeof Card>;

export default meta;

type Story = StoryObj<typeof meta>;

function example(fields: ExampleFields): Pick<Story, "parameters" | "render"> {
  return { parameters: { prism: { example: fields } }, render: (args) => renderCardExample(args, fields) };
}

/** Card.yaml example `solid-metric` */
export const SolidMetric: Story = {
  name: "solid-metric",
  args: {"variant":"solid","title":"Line output","caption":"Last 24 hours","hero":{"value":"86","trailing":".4","unit":"%"}},
  ...example({"id":"solid-metric"}),
};

/** Card.yaml example `vivid-default-kpi`: the unit sits in the caption, because the hero block on vivid holds only the value */
export const VividDefaultKpi: Story = {
  name: "vivid-default-kpi",
  args: {"variant":"vivid","title":"Average yield","caption":"Dollars per batch","hero":{"value":"$2,450"}},
  ...example({"id":"vivid-default-kpi","description":"the unit sits in the caption, because the hero block on vivid holds only the value"}),
};

/** Card.yaml example `vivid-pair`: a 2×2 of vivid cards, one slot pair on the diagonals */
export const VividPair: Story = {
  name: "vivid-pair",
  args: {"variant":"vivid","size":"compact","title":"Average yield"},
  ...example({"id":"vivid-pair","grid":["1","2","2","1"],"description":"a 2×2 of vivid cards, one slot pair on the diagonals"}),
};

/** Card.yaml example `glass-vehicle` */
export const GlassVehicle: Story = {
  name: "glass-vehicle",
  args: {"variant":"glass","backdrop":"image","title":"Unit 4417","caption":"21.11.2026, 14:05:22"},
  ...example({"id":"glass-vehicle","surface":"image"}),
};

/** Card.yaml example `glass-selected` */
export const GlassSelected: Story = {
  name: "glass-selected",
  args: {"variant":"glass","backdrop":"image","title":"Unit 4417","isSelected":true},
  ...example({"id":"glass-selected","surface":"image"}),
};

/** Card.yaml example `tinted-focus` */
export const TintedFocus: Story = {
  name: "tinted-focus",
  tags: ["schemes-light"],
  args: {"variant":"tinted","title":"Sensor","caption":"Active","icon":"object.gps"},
  ...example({"id":"tinted-focus","schemes":["light"]}),
};

/** Card.yaml example `compact` */
export const Compact: Story = {
  name: "compact",
  args: {"variant":"solid","size":"compact","title":"Queued","hero":{"value":"37"}},
  ...example({"id":"compact"}),
};
