// Generated by scripts/stories.ts from spec/components/Chip.yaml (specVersion 1). Do not edit;
// run `pnpm --filter @iiiivaska/prism-gallery stories` after the spec changes.
import type { Meta, StoryObj } from "@storybook/react-vite";
import { fn } from "storybook/test";
import { Chip } from "@iiiivaska/prism-react";
import { renderChipExample, type ChipExampleArgs, type ExampleFields } from "../harness/examples.tsx";

const meta = {
  title: "Chip",
  component: Chip,
  tags: ["vrt"],
  args: { onPress: fn(), onRemove: fn() },
  parameters: { prism: { component: "Chip", specVersion: 1 } },
} satisfies Meta<typeof Chip>;

export default meta;

type Story = StoryObj<ChipExampleArgs>;

function example(fields: ExampleFields): Pick<Story, "parameters" | "render"> {
  return { parameters: { prism: { example: fields } }, render: (args) => renderChipExample(args, fields) };
}

/** Chip.yaml example `default-sm` */
export const DefaultSm: Story = {
  name: "default-sm",
  args: {"label":"Last 24 hours","size":"sm"},
  ...example({"id":"default-sm"}),
};

/** Chip.yaml example `selected`: a filter chip that is on */
export const Selected: Story = {
  name: "selected",
  args: {"label":"Last 24 hours","isSelected":true},
  ...example({"id":"selected","description":"a filter chip that is on"}),
};

/** Chip.yaml example `with-leading-icon` */
export const WithLeadingIcon: Story = {
  name: "with-leading-icon",
  args: {"label":"Routes","leadingIcon":"action.filter"},
  ...example({"id":"with-leading-icon"}),
};

/** Chip.yaml example `removable` */
export const Removable: Story = {
  name: "removable",
  args: {"label":"North yard","isRemovable":true},
  ...example({"id":"removable"}),
};

/** Chip.yaml example `identifier-copy`: an identifier chip whose press copies it; action.copy shows what the press does, and the name is the identifier itself */
export const IdentifierCopy: Story = {
  name: "identifier-copy",
  args: {"label":"B-4417","trailingIcon":"action.copy"},
  ...example({"id":"identifier-copy","description":"an identifier chip whose press copies it; action.copy shows what the press does, and the name is the identifier itself"}),
};

/** Chip.yaml example `md-size` */
export const MdSize: Story = {
  name: "md-size",
  args: {"label":"Depots","size":"md","leadingIcon":"object.map-pin"},
  ...example({"id":"md-size"}),
};

/** Chip.yaml example `disabled` */
export const Disabled: Story = {
  name: "disabled",
  args: {"label":"Last 24 hours","isDisabled":true},
  ...example({"id":"disabled"}),
};

/** Chip.yaml example `md-with-avatar`: an identifier chip whose leading position holds an Avatar, drawn at size sm and decorative; only the md chip leaves it room, concentric with the pill's leading end */
export const MdWithAvatar: Story = {
  name: "md-with-avatar",
  args: {"label":"Anna Petrova","size":"md","avatar":{"name":"Anna Petrova"}},
  ...example({"id":"md-with-avatar","description":"an identifier chip whose leading position holds an Avatar, drawn at size sm and decorative; only the md chip leaves it room, concentric with the pill's leading end"}),
};

/** Chip.yaml example `on-map`: over a map the chip renders the glass chip recipe and carries the primary glass foreground only */
export const OnMap: Story = {
  name: "on-map",
  tags: ["glass"],
  args: {"label":"Depots","leadingIcon":"object.map-pin"},
  ...example({"id":"on-map","surface":"map","description":"over a map the chip renders the glass chip recipe and carries the primary glass foreground only"}),
};

/** Chip.yaml example `selected-on-map`: over media selection adds status.check in the leading slot, because every tone on the chip is one glass foreground */
export const SelectedOnMap: Story = {
  name: "selected-on-map",
  tags: ["glass"],
  args: {"label":"Depots","isSelected":true},
  ...example({"id":"selected-on-map","surface":"map","description":"over media selection adds status.check in the leading slot, because every tone on the chip is one glass foreground"}),
};

/** Chip.yaml example `on-vivid` */
export const OnVivid: Story = {
  name: "on-vivid",
  tags: ["glass"],
  args: {"label":"Yield"},
  ...example({"id":"on-vivid","surface":"vivid"}),
};

/** Chip.yaml example `on-glass-over-image` */
export const OnGlassOverImage: Story = {
  name: "on-glass-over-image",
  tags: ["glass"],
  args: {"label":"In service"},
  ...example({"id":"on-glass-over-image","surface":"glass","backdrop":"image"}),
};

/** Chip.yaml example `russian-label`: Russian labels widen the chip instead of truncating */
export const RussianLabel: Story = {
  name: "russian-label",
  args: {"label":"Последние 24 часа","isSelected":true},
  ...example({"id":"russian-label","description":"Russian labels widen the chip instead of truncating"}),
};
