// Generated by scripts/stories.ts from spec/components/Divider.yaml (specVersion 2). Do not edit;
// run `pnpm --filter @iiiivaska/prism-gallery stories` after the spec changes.
import type { Meta, StoryObj } from "@storybook/react-vite";
import { Divider } from "@iiiivaska/prism-react";
import { renderDividerExample, type ExampleFields } from "../harness/examples.tsx";

const meta = {
  title: "Divider",
  component: Divider,
  tags: ["vrt"],
  parameters: { prism: { component: "Divider", specVersion: 2 } },
} satisfies Meta<typeof Divider>;

export default meta;

type Story = StoryObj<typeof meta>;

function example(fields: ExampleFields): Pick<Story, "parameters" | "render"> {
  return { parameters: { prism: { example: fields } }, render: (args) => renderDividerExample(args, fields) };
}

/** Divider.yaml example `horizontal` */
export const Horizontal: Story = {
  name: "horizontal",
  args: {"orientation":"horizontal","inset":"none"},
  ...example({"id":"horizontal"}),
};

/** Divider.yaml example `horizontal-inset`: a row rule inside a card, starting at the content edge */
export const HorizontalInset: Story = {
  name: "horizontal-inset",
  args: {"orientation":"horizontal","inset":"content"},
  ...example({"id":"horizontal-inset","surface":"solid","description":"a row rule inside a card, starting at the content edge"}),
};

/** Divider.yaml example `vertical`: the edge between two columns of one panel */
export const Vertical: Story = {
  name: "vertical",
  args: {"orientation":"vertical","inset":"none"},
  ...example({"id":"vertical","surface":"solid","description":"the edge between two columns of one panel"}),
};

/** Divider.yaml example `semantic`: the one case where the rule is the grouping cue: exposed as a separator on the web; Apple has no separator role (notes.platform.ios) */
export const Semantic: Story = {
  name: "semantic",
  args: {"orientation":"horizontal","isDecorative":false},
  ...example({"id":"semantic","description":"the one case where the rule is the grouping cue: exposed as a separator on the web; Apple has no separator role (notes.platform.ios)"}),
};

/** Divider.yaml example `on-vivid`: on vivid the line is `color.border.on-media`, kept out of the bloom */
export const OnVivid: Story = {
  name: "on-vivid",
  args: {"orientation":"horizontal","inset":"content"},
  ...example({"id":"on-vivid","surface":"vivid","description":"on vivid the line is `color.border.on-media`, kept out of the bloom"}),
};

/** Divider.yaml example `on-glass-over-map` */
export const OnGlassOverMap: Story = {
  name: "on-glass-over-map",
  tags: ["glass"],
  args: {"orientation":"horizontal","inset":"content"},
  ...example({"id":"on-glass-over-map","surface":"glass","backdrop":"map"}),
};
