// Generated by scripts/stories.ts from spec/components/IconButton.yaml (specVersion 2). Do not edit;
// run `pnpm --filter @iiiivaska/prism-gallery stories` after the spec changes.
import type { Meta, StoryObj } from "@storybook/react-vite";
import { fn } from "storybook/test";
import { IconButton } from "@iiiivaska/prism-react";
import { renderIconButtonExample, type ExampleFields } from "../harness/examples.tsx";

const meta = {
  title: "IconButton",
  component: IconButton,
  tags: ["vrt"],
  args: { onPress: fn() },
  parameters: { prism: { component: "IconButton", specVersion: 2 } },
} satisfies Meta<typeof IconButton>;

export default meta;

type Story = StoryObj<typeof meta>;

function example(fields: ExampleFields): Pick<Story, "parameters" | "render"> {
  return { parameters: { prism: { example: fields } }, render: (args) => renderIconButtonExample(args, fields) };
}

/** IconButton.yaml example `secondary-md` */
export const SecondaryMd: Story = {
  name: "secondary-md",
  args: {"variant":"secondary","size":"md","glyph":"action.settings","label":"Open settings"},
  ...example({"id":"secondary-md"}),
};

/** IconButton.yaml example `primary-md` */
export const PrimaryMd: Story = {
  name: "primary-md",
  args: {"variant":"primary","size":"md","glyph":"action.add","label":"Add a site"},
  ...example({"id":"primary-md"}),
};

/** IconButton.yaml example `ghost-md` */
export const GhostMd: Story = {
  name: "ghost-md",
  args: {"variant":"ghost","size":"md","glyph":"action.filter","label":"Filter results"},
  ...example({"id":"ghost-md"}),
};

/** IconButton.yaml example `plain-sm`: the corner affordance of a Card, whose hit region is 44 pt under touch */
export const PlainSm: Story = {
  name: "plain-sm",
  args: {"variant":"plain","size":"sm","glyph":"nav.open","label":"Open details"},
  ...example({"id":"plain-sm","description":"the corner affordance of a Card, whose hit region is 44 pt under touch"}),
};

/** IconButton.yaml example `danger-md` */
export const DangerMd: Story = {
  name: "danger-md",
  args: {"variant":"danger","size":"md","glyph":"action.delete","label":"Delete route"},
  ...example({"id":"danger-md"}),
};

/** IconButton.yaml example `selected-in-group`: the one selected circle in a view switcher; its siblings stay hairline rings */
export const SelectedInGroup: Story = {
  name: "selected-in-group",
  args: {"variant":"ghost","size":"md","glyph":"object.map","label":"Map view","isSelected":true},
  ...example({"id":"selected-in-group","description":"the one selected circle in a view switcher; its siblings stay hairline rings"}),
};

/** IconButton.yaml example `lg-touch` */
export const LgTouch: Story = {
  name: "lg-touch",
  args: {"variant":"primary","size":"lg","glyph":"action.play","label":"Start the run"},
  ...example({"id":"lg-touch"}),
};

/** IconButton.yaml example `disabled` */
export const Disabled: Story = {
  name: "disabled",
  args: {"variant":"secondary","size":"md","glyph":"action.refresh","label":"Refresh readings","isDisabled":true},
  ...example({"id":"disabled"}),
};

/** IconButton.yaml example `on-vivid` */
export const OnVivid: Story = {
  name: "on-vivid",
  args: {"variant":"ghost","size":"md","glyph":"nav.open","label":"Open the yield card"},
  ...example({"id":"on-vivid","surface":"vivid"}),
};

/** IconButton.yaml example `on-glass-over-map` */
export const OnGlassOverMap: Story = {
  name: "on-glass-over-map",
  tags: ["glass"],
  args: {"variant":"primary","size":"md","glyph":"action.locate","label":"Center on the vehicle"},
  ...example({"id":"on-glass-over-map","surface":"glass","backdrop":"map"}),
};

/** IconButton.yaml example `label-ru`: a long Russian name, which is spoken and never drawn, so the circle does not change */
export const LabelRu: Story = {
  name: "label-ru",
  args: {"variant":"secondary","size":"md","glyph":"action.refresh","label":"Обновить показания линии"},
  ...example({"id":"label-ru","description":"a long Russian name, which is spoken and never drawn, so the circle does not change"}),
};

/** IconButton.yaml example `with-badge`: the badge slot filled - a count Badge anchored space.1 outside the circle's top-trailing corner, hidden itself and read into the button's accessibility value, "3 unread" */
export const WithBadge: Story = {
  name: "with-badge",
  args: {"variant":"secondary","size":"md","glyph":"object.notification","label":"Open notifications","badge":{"variant":"count","tone":"neutral","count":3,"label":"unread"}},
  ...example({"id":"with-badge","description":"the badge slot filled - a count Badge anchored space.1 outside the circle's top-trailing corner, hidden itself and read into the button's accessibility value, \"3 unread\""}),
};
