// Generated by scripts/stories.ts from spec/components/Icon.yaml (specVersion 3). Do not edit;
// run `pnpm --filter @iiiivaska/prism-gallery stories` after the spec changes.
import type { Meta, StoryObj } from "@storybook/react-vite";
import { Icon } from "@iiiivaska/prism-react";
import { renderIconExample, type ExampleFields } from "../harness/examples.tsx";

const meta = {
  title: "Icon",
  component: Icon,
  tags: ["vrt"],
  parameters: { prism: { component: "Icon", specVersion: 3 } },
} satisfies Meta<typeof Icon>;

export default meta;

type Story = StoryObj<typeof meta>;

function example(fields: ExampleFields): Pick<Story, "parameters" | "render"> {
  return { parameters: { prism: { example: fields } }, render: (args) => renderIconExample(args, fields) };
}

/** Icon.yaml example `control-md` */
export const ControlMd: Story = {
  name: "control-md",
  args: {"name":"action.settings","size":"md","tone":"primary"},
  ...example({"id":"control-md"}),
};

/** Icon.yaml example `corner-sm`: the open affordance a Card pins to its top-right corner */
export const CornerSm: Story = {
  name: "corner-sm",
  args: {"name":"nav.open","size":"sm","tone":"secondary"},
  ...example({"id":"corner-sm","description":"the open affordance a Card pins to its top-right corner"}),
};

/** Icon.yaml example `display-lg`: a large illustrative glyph in the thin cut; the map is an outline on both stacks, so the thinner stroke shows */
export const DisplayLg: Story = {
  name: "display-lg",
  args: {"name":"object.map","size":"lg","weight":"display","tone":"secondary"},
  ...example({"id":"display-lg","description":"a large illustrative glyph in the thin cut; the map is an outline on both stacks, so the thinner stroke shows"}),
};

/** Icon.yaml example `status-filled` */
export const StatusFilled: Story = {
  name: "status-filled",
  args: {"name":"status.warning","size":"sm","style":"filled","tone":"warning"},
  ...example({"id":"status-filled"}),
};

/** Icon.yaml example `accent-mark` */
export const AccentMark: Story = {
  name: "accent-mark",
  args: {"name":"object.gps","size":"sm","tone":"accent"},
  ...example({"id":"accent-mark"}),
};

/** Icon.yaml example `inherit-in-row`: inside a ListRow, where the glyph takes the row's own foreground */
export const InheritInRow: Story = {
  name: "inherit-in-row",
  args: {"name":"status.online","size":"sm","tone":"inherit"},
  ...example({"id":"inherit-in-row","description":"inside a ListRow, where the glyph takes the row's own foreground"}),
};

/** Icon.yaml example `decorative` */
export const Decorative: Story = {
  name: "decorative",
  args: {"name":"object.chart","size":"md","isDecorative":true},
  ...example({"id":"decorative"}),
};

/** Icon.yaml example `named-standalone`: the one path assistive technology reads - a `label` and `isDecorative` false make the glyph an image named by that label. The lock sits beside a route's name with no word of its own on screen, which is when a glyph needs a name; a status glyph never takes this path, because a status is its glyph plus a visible word (ADR-0011 rule 4) */
export const NamedStandalone: Story = {
  name: "named-standalone",
  args: {"name":"object.lock","size":"sm","tone":"secondary","label":"Locked for editing","isDecorative":false},
  ...example({"id":"named-standalone","description":"the one path assistive technology reads - a `label` and `isDecorative` false make the glyph an image named by that label. The lock sits beside a route's name with no word of its own on screen, which is when a glyph needs a name; a status glyph never takes this path, because a status is its glyph plus a visible word (ADR-0011 rule 4)"}),
};

/** Icon.yaml example `on-vivid` */
export const OnVivid: Story = {
  name: "on-vivid",
  args: {"name":"nav.open","size":"sm","tone":"primary"},
  ...example({"id":"on-vivid","surface":"vivid"}),
};

/** Icon.yaml example `on-glass-over-map` */
export const OnGlassOverMap: Story = {
  name: "on-glass-over-map",
  tags: ["glass"],
  args: {"name":"object.map-pin","size":"md","tone":"secondary"},
  ...example({"id":"on-glass-over-map","surface":"glass","backdrop":"map"}),
};

/** Icon.yaml example `on-glass-light-over-image` */
export const OnGlassLightOverImage: Story = {
  name: "on-glass-light-over-image",
  tags: ["glass"],
  args: {"name":"action.play","size":"md","tone":"primary"},
  ...example({"id":"on-glass-light-over-image","surface":"glassLight","backdrop":"image"}),
};
