// Generated by scripts/stories.ts from spec/components/Surface.yaml (specVersion 3). Do not edit;
// run `pnpm --filter @iiiivaska/prism-gallery stories` after the spec changes.
import type { Meta, StoryObj } from "@storybook/react-vite";
import { Surface } from "@iiiivaska/prism-react";
import { renderSurfaceExample, type ExampleFields } from "../harness/examples.tsx";

const meta = {
  title: "Surface",
  component: Surface,
  tags: ["vrt"],
  parameters: { prism: { component: "Surface", specVersion: 3 } },
} satisfies Meta<typeof Surface>;

export default meta;

type Story = StoryObj<typeof meta>;

function example(fields: ExampleFields): Pick<Story, "parameters" | "render"> {
  return { parameters: { prism: { example: fields } }, render: (args) => renderSurfaceExample(args, fields) };
}

/** Surface.yaml example `solid-card` */
export const SolidCard: Story = {
  name: "solid-card",
  args: {"material":"solid","radius":"card"},
  ...example({"id":"solid-card"}),
};

/** Surface.yaml example `vivid-default` */
export const VividDefault: Story = {
  name: "vivid-default",
  args: {"material":"vivid","radius":"card"},
  ...example({"id":"vivid-default"}),
};

/** Surface.yaml example `vivid-pair`: a 2×2 of vivid tiles, one slot pair on the diagonals */
export const VividPair: Story = {
  name: "vivid-pair",
  args: {"material":"vivid","radius":"tile"},
  ...example({"id":"vivid-pair","grid":["1","2","2","1"],"description":"a 2×2 of vivid tiles, one slot pair on the diagonals"}),
};

/** Surface.yaml example `glass-over-map` */
export const GlassOverMap: Story = {
  name: "glass-over-map",
  args: {"material":"glass","backdrop":"map","radius":"card","elevation":"overlay"},
  ...example({"id":"glass-over-map","surface":"map"}),
};

/** Surface.yaml example `glass-light-over-image` */
export const GlassLightOverImage: Story = {
  name: "glass-light-over-image",
  args: {"material":"glassLight","backdrop":"image","radius":"card"},
  ...example({"id":"glass-light-over-image","surface":"image"}),
};

/** Surface.yaml example `glass-selected` */
export const GlassSelected: Story = {
  name: "glass-selected",
  args: {"material":"glass","backdrop":"image","radius":"card","selected":true},
  ...example({"id":"glass-selected","surface":"image"}),
};

/** Surface.yaml example `inverse-pill` */
export const InversePill: Story = {
  name: "inverse-pill",
  args: {"material":"inverse","radius":"pill","padding":"none"},
  ...example({"id":"inverse-pill"}),
};

/** Surface.yaml example `accent-tile` */
export const AccentTile: Story = {
  name: "accent-tile",
  args: {"material":"accent","radius":"tile"},
  ...example({"id":"accent-tile"}),
};
