// Generated by scripts/stories.ts from spec/components/Text.yaml (specVersion 2). Do not edit;
// run `pnpm --filter @iiiivaska/prism-gallery stories` after the spec changes.
import type { Meta, StoryObj } from "@storybook/react-vite";
import { Text } from "@iiiivaska/prism-react";
import { renderTextExample, type ExampleFields } from "../harness/examples.tsx";

const meta = {
  title: "Text",
  component: Text,
  tags: ["vrt"],
  parameters: { prism: { component: "Text", specVersion: 2 } },
} satisfies Meta<typeof Text>;

export default meta;

type Story = StoryObj<typeof meta>;

function example(fields: ExampleFields): Pick<Story, "parameters" | "render"> {
  return { parameters: { prism: { example: fields } }, render: (args) => renderTextExample(args, fields) };
}

/** Text.yaml example `hero-metric`: 86.4 % with the decimal dimmed and the unit hung */
export const HeroMetric: Story = {
  name: "hero-metric",
  args: {"role":"metric-xl","tone":"primary","trailing":".4","unit":"%"},
  ...example({"id":"hero-metric","description":"86.4 % with the decimal dimmed and the unit hung"}),
};

/** Text.yaml example `title-two-tone`: second line rendered with tone secondary */
export const TitleTwoTone: Story = {
  name: "title-two-tone",
  args: {"role":"title-lg","tone":"primary"},
  ...example({"id":"title-two-tone","description":"second line rendered with tone secondary"}),
};

/** Text.yaml example `caption` */
export const Caption: Story = {
  name: "caption",
  args: {"role":"caption","tone":"secondary"},
  ...example({"id":"caption"}),
};

/** Text.yaml example `on-vivid` */
export const OnVivid: Story = {
  name: "on-vivid",
  args: {"role":"headline","tone":"primary"},
  ...example({"id":"on-vivid","surface":"vivid"}),
};

/** Text.yaml example `on-glass-over-map`: the scheme's glass over a map, where the secondary tone is color.text.on-glass-fill-secondary */
export const OnGlassOverMap: Story = {
  name: "on-glass-over-map",
  tags: ["glass"],
  args: {"role":"caption","tone":"secondary"},
  ...example({"id":"on-glass-over-map","surface":"glass","backdrop":"map","description":"the scheme's glass over a map, where the secondary tone is color.text.on-glass-fill-secondary"}),
};

/** Text.yaml example `data-tabular` */
export const DataTabular: Story = {
  name: "data-tabular",
  args: {"role":"data","numeric":"tabular"},
  ...example({"id":"data-tabular"}),
};
