// Generated by scripts/stories.ts from spec/components/Toggle.yaml (specVersion 1). Do not edit;
// run `pnpm --filter @iiiivaska/prism-gallery stories` after the spec changes.
import type { Meta, StoryObj } from "@storybook/react-vite";
import { fn } from "storybook/test";
import { Toggle } from "@iiiivaska/prism-react";
import { renderToggleExample, type ExampleFields } from "../harness/examples.tsx";

const meta = {
  title: "Toggle",
  component: Toggle,
  tags: ["vrt"],
  args: { onChange: fn() },
  parameters: { prism: { component: "Toggle", specVersion: 1 } },
} satisfies Meta<typeof Toggle>;

export default meta;

type Story = StoryObj<typeof meta>;

function example(fields: ExampleFields): Pick<Story, "parameters" | "render"> {
  return { parameters: { prism: { example: fields } }, render: (args) => renderToggleExample(args, fields) };
}

/** Toggle.yaml example `off` */
export const Off: Story = {
  name: "off",
  args: {"isOn":false,"label":"Night shading"},
  ...example({"id":"off"}),
};

/** Toggle.yaml example `on` */
export const On: Story = {
  name: "on",
  args: {"isOn":true,"label":"Night shading"},
  ...example({"id":"on"}),
};

/** Toggle.yaml example `on-disabled` */
export const OnDisabled: Story = {
  name: "on-disabled",
  args: {"isOn":true,"label":"Night shading","isDisabled":true},
  ...example({"id":"on-disabled"}),
};

/** Toggle.yaml example `bare`: no visible label; the switch alone, named by its hidden `label`, which is what a row that draws the words hands it (ADR-0041) */
export const Bare: Story = {
  name: "bare",
  args: {"isOn":false,"label":"Night shading","labelVisibility":"hidden"},
  ...example({"id":"bare","description":"no visible label; the switch alone, named by its hidden `label`, which is what a row that draws the words hands it (ADR-0041)"}),
};

/** Toggle.yaml example `on-vivid` */
export const OnVivid: Story = {
  name: "on-vivid",
  args: {"isOn":true,"label":"Live readings"},
  ...example({"id":"on-vivid","surface":"vivid"}),
};

/** Toggle.yaml example `off-on-vivid`: the off track on a gradient - no fill, a white ring and a white knob */
export const OffOnVivid: Story = {
  name: "off-on-vivid",
  args: {"isOn":false,"label":"Live readings"},
  ...example({"id":"off-on-vivid","surface":"vivid","description":"the off track on a gradient - no fill, a white ring and a white knob"}),
};

/** Toggle.yaml example `on-glass-over-map` */
export const OnGlassOverMap: Story = {
  name: "on-glass-over-map",
  tags: ["glass"],
  args: {"isOn":true,"label":"Follow the vehicle"},
  ...example({"id":"on-glass-over-map","surface":"glass","backdrop":"map"}),
};

/** Toggle.yaml example `label-ru`: a long Russian label; it wraps and the row grows, while the track keeps its height on the label's first line */
export const LabelRu: Story = {
  name: "label-ru",
  args: {"isOn":false,"label":"Показывать ночное затенение маршрута следования"},
  ...example({"id":"label-ru","description":"a long Russian label; it wraps and the row grows, while the track keeps its height on the label's first line"}),
};
