/// <reference types="node" />
/**
 * Discovery for the Icons screen (docs/showcase.md §1, §4): the drawing half of the registry.
 *
 * `Icon` (spec/components/Icon.yaml) is implemented on neither stack, and `Glyph` — the internal,
 * decorative glyph that Button and Card draw — is not exported by `@iiiivaska/prism-react`. So the
 * showcase cannot render a Prism component here, and it says so on the screen. What it *can* do
 * honestly is draw each registry entry from the registry's own binding: `iconRegistry[id].phosphor`
 * is the Phosphor name (ADR-0013 decision 2), and `@phosphor-icons/core` ships that name as one SVG
 * per cut. This plugin reads those files at build time and hands the markup over as
 * `virtual:prism/glyphs`.
 *
 * Which ids exist, and which Phosphor name each one binds, are read from the *generated* registry
 * (`web/packages/react/src/generated/icons.ts`, written by `pnpm icons:build` from
 * spec/icons/registry.json), so an id that lands in the registry is drawn here with no edit to the
 * app, and an id whose Phosphor asset is missing fails the build instead of rendering a blank box.
 */
import { createRequire } from "node:module";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import type { Plugin } from "vite";

const MODULE_ID = "virtual:prism/glyphs";
const RESOLVED_ID = `\0${MODULE_ID}`;

/** The Phosphor cuts `iconWeights` and `iconStyles` reach (web/packages/react/src/generated/icons.ts). */
const CUTS = ["thin", "light", "regular", "bold", "fill", "duotone"] as const;
export type PhosphorCut = (typeof CUTS)[number];

/** `"action.add": { phosphor: "plus", …` — the binding, from the generated registry. */
export function readBindings(source: string): Map<string, string> {
  const bindings = new Map<string, string>();
  for (const match of source.matchAll(/"([\w.-]+)":\s*\{\s*phosphor:\s*"([\w-]+)"/g)) {
    const id = match[1];
    const phosphor = match[2];
    if (id !== undefined && phosphor !== undefined) bindings.set(id, phosphor);
  }
  return bindings;
}

/** The markup inside `<svg …>…</svg>`: what a specimen drops into its own sized, coloured `<svg>`. */
export function innerMarkup(svg: string): string {
  const open = svg.indexOf(">");
  const close = svg.lastIndexOf("</svg>");
  if (open === -1 || close === -1) throw new Error("not an SVG document");
  return svg.slice(open + 1, close).trim();
}

export interface GlyphOptions {
  readonly repositoryRoot: string;
}

export function prismGlyphs(options: GlyphOptions): Plugin {
  const registryFile = join(options.repositoryRoot, "web", "packages", "react", "src", "generated", "icons.ts");
  const require = createRequire(import.meta.url);

  return {
    name: "prism-showcase-glyphs",

    resolveId(id) {
      return id === MODULE_ID ? RESOLVED_ID : null;
    },

    load(id) {
      if (id !== RESOLVED_ID) return null;
      this.addWatchFile(registryFile);

      const bindings = readBindings(readFileSync(registryFile, "utf8"));
      if (bindings.size === 0) throw new Error(`No icon bindings found in ${registryFile}; the generated registry's shape changed`);

      const glyphs: Record<string, Record<string, string>> = {};
      for (const [iconName, phosphor] of bindings) {
        const cuts: Record<string, string> = {};
        for (const cut of CUTS) {
          // The `fill` and `duotone` cuts spell the plain name; the rest carry the cut as a suffix.
          const file = cut === "regular" ? `${phosphor}.svg` : `${phosphor}-${cut}.svg`;
          let resolved: string;
          try {
            resolved = require.resolve(`@phosphor-icons/core/assets/${cut}/${file}`);
          } catch {
            throw new Error(`@phosphor-icons/core has no ${cut} cut of "${phosphor}" (registry id ${iconName}); run \`pnpm icons:validate\``);
          }
          cuts[cut] = innerMarkup(readFileSync(resolved, "utf8"));
        }
        glyphs[iconName] = cuts;
      }

      return [
        "// Generated by web/apps/showcase/plugins/glyphs.ts from the icon registry and @phosphor-icons/core.",
        `export const glyphs = ${JSON.stringify(glyphs)};`,
        `export const glyphCuts = ${JSON.stringify(CUTS)};`,
        "",
      ].join("\n");
    },
  };
}
