// Generated by tools/tokens from tokens/prism.resolver.json. Do not edit; run `pnpm tokens:build`.
import SwiftUI

/// The color space of a literal color (ARCHITECTURE §7.2): authored sRGB overlays stay sRGB, every other color is Display P3.
public enum DSColorSpace: String, CaseIterable, Hashable, Sendable {
    case sRGB, displayP3
}

/// A literal color: the value behind a catalog entry, a shadow layer or a gradient stop.
public struct DSRGBA: Hashable, Sendable {
    public let space: DSColorSpace
    public let red: Double
    public let green: Double
    public let blue: Double
    public let alpha: Double

    public init(_ space: DSColorSpace, _ red: Double, _ green: Double, _ blue: Double, _ alpha: Double) {
        self.space = space
        self.red = red
        self.green = green
        self.blue = blue
        self.alpha = alpha
    }

    public var color: Color {
        Color(space == .sRGB ? .sRGB : .displayP3, red: red, green: green, blue: blue, opacity: alpha)
    }
}

/// Apple's two-parameter spring (ADR-0023 §1–§3) with the physics triplet the web runtime configures Motion with.
/// `settle` is the ε = 0.001 displacement settle in seconds, never SwiftUI's own settling estimate (ADR-0023 §3).
public struct DSSpringToken: Hashable, Sendable {
    public let duration: Double
    public let bounce: Double
    public let blendDuration: Double
    public let settle: Double
    public let mass: Double
    public let stiffness: Double
    public let damping: Double

    public init(duration: Double, bounce: Double, blendDuration: Double, settle: Double, mass: Double, stiffness: Double, damping: Double) {
        self.duration = duration
        self.bounce = bounce
        self.blendDuration = blendDuration
        self.settle = settle
        self.mass = mass
        self.stiffness = stiffness
        self.damping = damping
    }

    public var spring: Spring { Spring(duration: duration, bounce: bounce) }

    public var animation: Animation { .spring(spring, blendDuration: blendDuration) }
}

/// A cubic Bézier easing (ARCHITECTURE §7.5).
public struct DSCubicBezier: Hashable, Sendable {
    public let x1: Double
    public let y1: Double
    public let x2: Double
    public let y2: Double

    public init(x1: Double, y1: Double, x2: Double, y2: Double) {
        self.x1 = x1
        self.y1 = y1
        self.x2 = x2
        self.y2 = y2
    }

    public func animation(duration: TimeInterval) -> Animation { .timingCurve(x1, y1, x2, y2, duration: duration) }
}

/// A transition without a spring in every context (seconds); a spring token is a `DSSpringToken` (ARCHITECTURE §7.6).
public struct DSTransitionToken: Hashable, Sendable {
    public let duration: TimeInterval
    public let delay: TimeInterval
    public let curve: DSCubicBezier
    public let spring: DSSpringToken?

    public init(duration: TimeInterval, delay: TimeInterval, curve: DSCubicBezier, spring: DSSpringToken?) {
        self.duration = duration
        self.delay = delay
        self.curve = curve
        self.spring = spring
    }
}

/// One shadow layer with CSS blur semantics; DSCore converts the blur to a SwiftUI radius (ARCHITECTURE §7.8).
public struct DSShadowLayer: Hashable, Sendable {
    public let color: DSRGBA
    public let x: CGFloat
    public let y: CGFloat
    public let blur: CGFloat
    public let spread: CGFloat
    public let inset: Bool

    public init(color: DSRGBA, x: CGFloat, y: CGFloat, blur: CGFloat, spread: CGFloat, inset: Bool) {
        self.color = color
        self.x = x
        self.y = y
        self.blur = blur
        self.spread = spread
        self.inset = inset
    }
}

/// A shadow: its layers, back to front.
public struct DSShadowToken: Hashable, Sendable {
    public let layers: [DSShadowLayer]

    public init(layers: [DSShadowLayer]) {
        self.layers = layers
    }
}

/// A gradient stop; `location` runs from 0 to 1.
public struct DSGradientStop: Hashable, Sendable {
    public let color: DSRGBA
    public let location: Double

    public init(color: DSRGBA, location: Double) {
        self.color = color
        self.location = location
    }
}

/// A vivid gradient (ARCHITECTURE §7.9, ADR-0022 §4): `angle` in degrees with CSS semantics, which DSCore turns into
/// start and end points for the surface size; grain and bloom belong to the gradient (ADR-0024 §6).
/// Interpolation: OKLab on both stacks (P1-5's parity decision, ARCHITECTURE §7.9, §16.3). The web writes `in oklab`;
/// DSCore (P3-1) draws the stops with `Gradient.ColorSpace.perceptual` once that space is verified to be OKLab
/// (ARCHITECTURE §16.1 V14), else with stops resampled in OKLab. SwiftUI's default, `.device`, would not match the web.
public struct DSGradientToken: Hashable, Sendable {
    public let stops: [DSGradientStop]
    public let angle: Double
    public let grain: Double
    public let scheme: DSColorScheme?
    public let bloomAlpha: Double
    public let bloomBlur: CGFloat

    public init(stops: [DSGradientStop], angle: Double, grain: Double, scheme: DSColorScheme?, bloomAlpha: Double, bloomBlur: CGFloat) {
        self.stops = stops
        self.angle = angle
        self.grain = grain
        self.scheme = scheme
        self.bloomAlpha = bloomAlpha
        self.bloomBlur = bloomBlur
    }
}

/// The font slots a type role names (ADR-0020 §5).
public enum DSFontSlot: String, CaseIterable, Hashable, Sendable {
    case ui, display, mono
}

/// Figures (ADR-0021 §5): proportional renders the family default, tabular `.monospacedDigit()`.
public enum DSNumericSpacing: String, CaseIterable, Hashable, Sendable {
    case proportional, tabular
}

/// The Dynamic Type curve of a role (ADR-0021 §7). It mirrors `Font.TextStyle`, so `Sendable` does not depend on the SDK.
public enum DSTextStyle: String, CaseIterable, Hashable, Sendable {
    case largeTitle, title, title2, title3, headline, body, callout, subheadline, footnote, caption, caption2

    /// The SwiftUI text style for `@ScaledMetric(relativeTo:)`, which scales the role size (ADR-0021 §9).
    public var fontTextStyle: Font.TextStyle {
        switch self {
        case .largeTitle: .largeTitle
        case .title: .title
        case .title2: .title2
        case .title3: .title3
        case .headline: .headline
        case .body: .body
        case .callout: .callout
        case .subheadline: .subheadline
        case .footnote: .footnote
        case .caption: .caption
        case .caption2: .caption2
        }
    }
}

/// A type role (ADR-0021 §4, §6, §9): the size in points at the Large Dynamic Type size, the weight resolved for the
/// context (dark weight, Increase Contrast floor), the Bold Text weight, the line height as a multiple of the size and the
/// tracking as a fraction of it. The family comes from `DSBrand.faces` by slot. DSCore scales `size` with
/// `@ScaledMetric(relativeTo: textStyle.fontTextStyle)`.
public struct DSTypeRole: Hashable, Sendable {
    public let slot: DSFontSlot
    public let size: CGFloat
    public let weight: Int
    public let boldWeight: Int
    public let lineHeight: Double
    public let trackingEm: Double
    public let numeric: DSNumericSpacing
    public let textStyle: DSTextStyle

    public init(slot: DSFontSlot, size: CGFloat, weight: Int, boldWeight: Int, lineHeight: Double, trackingEm: Double, numeric: DSNumericSpacing, textStyle: DSTextStyle) {
        self.slot = slot
        self.size = size
        self.weight = weight
        self.boldWeight = boldWeight
        self.lineHeight = lineHeight
        self.trackingEm = trackingEm
        self.numeric = numeric
        self.textStyle = textStyle
    }
}

/// The line cap of a dashed stroke (ARCHITECTURE §7.10).
public enum DSLineCap: String, CaseIterable, Hashable, Sendable {
    case round, butt, square
}

/// The CSS keyword of a keyword stroke style (ARCHITECTURE §7.10).
public enum DSStrokeKeyword: String, CaseIterable, Hashable, Sendable {
    case solid, dashed, dotted, double, groove, ridge, outset, inset
}

/// A stroke style: a keyword, or a dash pattern in points with an optional line cap (ARCHITECTURE §7.10).
public struct DSStrokeStyle: Hashable, Sendable {
    public let keyword: DSStrokeKeyword?
    public let dash: [CGFloat]
    public let lineCap: DSLineCap?

    public init(dash: [CGFloat], lineCap: DSLineCap?) {
        keyword = nil
        self.dash = dash
        self.lineCap = lineCap
    }

    public init(keyword: DSStrokeKeyword) {
        self.keyword = keyword
        dash = []
        lineCap = nil
    }
}

/// A border: color, width in points and stroke style.
public struct DSBorderToken: Hashable, Sendable {
    public let color: DSRGBA
    public let width: CGFloat
    public let style: DSStrokeStyle

    public init(color: DSRGBA, width: CGFloat, style: DSStrokeStyle) {
        self.color = color
        self.width = width
        self.style = style
    }
}

/// The `preset` label of brand.json (ADR-0020 §5); nothing switches on it.
public enum DSFontPreset: String, CaseIterable, Hashable, Sendable {
    case signature, native
}

/// A system face (ADR-0020 §5): system-ui → default, ui-rounded → rounded, ui-monospace → monospaced, ui-serif → serif.
public enum DSSystemFontDesign: String, CaseIterable, Hashable, Sendable {
    case `default`, rounded, monospaced, serif

    public var fontDesign: Font.Design {
        switch self {
        case .`default`: .`default`
        case .rounded: .rounded
        case .monospaced: .monospaced
        case .serif: .serif
        }
    }
}

/// The face of a font slot on Apple (ADR-0020 §5, ADR-0021 §9): a family bundled in DSTokens (`file` relative to
/// `Resources/Fonts`, with the PostScript name Core Text exposes for each named instance) or a system design.
public struct DSFontFace: Hashable, Sendable {
    public let families: [String]
    public let file: String?
    public let postScriptNames: [Int: String]
    public let opticalSize: Double?
    public let system: DSSystemFontDesign?

    public init(families: [String], file: String?, postScriptNames: [Int: String], opticalSize: Double?, system: DSSystemFontDesign?) {
        self.families = families
        self.file = file
        self.postScriptNames = postScriptNames
        self.opticalSize = opticalSize
        self.system = system
    }

    /// The named instance for `weight`: the exact one, else the nearest heavier one, else the heaviest (ADR-0021 §9).
    /// Nil for a system face.
    public func postScriptName(for weight: Int) -> String? {
        if let exact = postScriptNames[weight] { return exact }
        let weights = postScriptNames.keys.sorted()
        guard let chosen = weights.first(where: { $0 > weight }) ?? weights.last else { return nil }
        return postScriptNames[chosen]
    }

    /// The bundled font file; nil for a system face. DSCore registers it (ADR-0021 §9).
    public var fileURL: URL? {
        guard let file else { return nil }
        return DSTokensBundle.bundle.resourceURL?.appendingPathComponent("Fonts", isDirectory: true).appendingPathComponent(file, isDirectory: false)
    }
}

/// DSTokens' resource bundle (the color catalog and the fonts), for DSCore and the catalog tests (ARCHITECTURE §9.7.2).
package enum DSTokensBundle {
    package static var bundle: Bundle { .module }
}
