// Generated by tools/tokens from tokens/prism.resolver.json and tools/tokens/config.ts (WEB_RUNTIME, PLATFORM_DEFAULTS). Do not edit; run `pnpm tokens:build`.

/// `colorScheme`, web attribute `data-ds-color-scheme`: `light` (default), `dark` (ADR-0019 §1).
public enum DSColorScheme: String, CaseIterable, Hashable, Sendable {
    case light, dark
}

/// `contrast`, web attribute `data-ds-contrast`: `standard` (default), `increased` (web `more`) (ADR-0019 §1).
public enum DSContrast: String, CaseIterable, Hashable, Sendable {
    case standard, increased
}

/// `transparency`, web attribute `data-ds-transparency`: `standard` (default), `reduced` (web `reduce`) (ADR-0019 §1).
public enum DSTransparency: String, CaseIterable, Hashable, Sendable {
    case standard, reduced
}

/// `density`, web attribute `data-ds-density`: `compact` (default), `regular`, `comfortable` (ADR-0019 §1).
public enum DSDensity: String, CaseIterable, Hashable, Sendable {
    case compact, regular, comfortable
}

/// `modality`, web attribute `data-ds-modality`: `pointer` (default), `touch` (ADR-0019 §1).
public enum DSModality: String, CaseIterable, Hashable, Sendable {
    case pointer, touch
}

/// `motion`, web attribute `data-ds-motion`: `standard` (default), `reduced` (web `reduce`) (ADR-0019 §1).
public enum DSMotionMode: String, CaseIterable, Hashable, Sendable {
    case standard, reduced
}

/// The context a token set resolves in (ARCHITECTURE §9.7.1): the brand, set once per scene by `DSTheme(brand:)`
/// (ADR-0020 §7), and the runtime axes of ADR-0019 §1. DSCore starts from `platformDefault` and overlays the
/// environment and `DSAccessibilityPolicy` (ADR-0019 §5).
public struct DSTokenContext: Hashable, Sendable {
    public var brand: DSBrand
    public var colorScheme: DSColorScheme
    public var contrast: DSContrast
    public var transparency: DSTransparency
    public var density: DSDensity
    public var modality: DSModality
    public var motion: DSMotionMode

    public init(
        brand: DSBrand = .default,
        colorScheme: DSColorScheme = .light,
        contrast: DSContrast = .standard,
        transparency: DSTransparency = .standard,
        density: DSDensity = .compact,
        modality: DSModality = .pointer,
        motion: DSMotionMode = .standard
    ) {
        self.brand = brand
        self.colorScheme = colorScheme
        self.contrast = contrast
        self.transparency = transparency
        self.density = density
        self.modality = modality
        self.motion = motion
    }

    /// The resolver default (the web root with nothing set): tests and the table evaluator. Not a device default.
    public static let `default` = DSTokenContext()

    /// Where DSCore starts on this OS (ADR-0019 §2); iPadOS switches to pointer while a pointing device is connected.
    #if os(watchOS)
    public static let platformDefault = DSTokenContext(colorScheme: .dark, density: .comfortable, modality: .touch)
    #elseif os(macOS)
    public static let platformDefault = DSTokenContext(density: .compact, modality: .pointer)
    #else
    public static let platformDefault = DSTokenContext(density: .regular, modality: .touch)
    #endif
}
