/// <reference types="node" />
/**
 * Builds dist/styles.css (ADR-0019 §4 item 6 as amended by ADR-0025): `compile` the source entry with
 * @tailwindcss/node against the generated tailwind.css, `build([])` with no candidates, then `optimize`,
 * so every `@variant ds-pointer` / `@variant ds-touch` becomes the generated attribute and media forms
 * and nothing of Tailwind is left. The grain tile rule is appended last (scripts/grain.ts).
 *
 *   node scripts/build-styles.ts           write dist/styles.css
 *   node scripts/build-styles.ts --stdout  print it instead
 *
 * `compileStyles` is exported for test/stylesheet.test.ts, which compiles fixtures the same way.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { compile, optimize, type CompileOptions } from "@tailwindcss/node";
import { grainTileRule } from "./grain.ts";

export const packageRoot = resolve(import.meta.dirname, "..");
export const stylesEntry = join(packageRoot, "src", "styles.css");
export const stylesOutput = join(packageRoot, "dist", "styles.css");

/** `Polyfills.None`; the enum is a `const enum` in a declaration file, which type stripping cannot read. */
const NO_POLYFILLS = 0 as NonNullable<CompileOptions["polyfills"]>;

const HEADER = `/* @iiiivaska/prism-react styles.css — generated by scripts/build-styles.ts from src/styles.css. Do not edit. */\n`;

/** Compiles one stylesheet the way the package build does; `base` resolves its imports. */
export async function compileStyles(css: string, base: string, file?: string): Promise<string> {
  const dependencies: string[] = [];
  const compiler = await compile(css, {
    base,
    ...(file === undefined ? {} : { from: file }),
    onDependency: (path) => dependencies.push(path),
    // No `@layer properties` fallback for @property and no color-mix() rewrite: Prism's browser floor
    // has both, and the fallback would add a global `*` rule outside `ds.*` (ADR-0019 §6.1, rule 9).
    polyfills: NO_POLYFILLS,
  });
  // Tailwind stamps its license banner on whatever it compiles; the output holds none of its code.
  const built = compiler.build([]).replace(/^\/\*! tailwindcss [^*]*\*\/\n?/m, "");
  return optimize(built, { minify: false, ...(file === undefined ? {} : { file }) }).code;
}

export async function buildStyles(): Promise<string> {
  const css = await compileStyles(readFileSync(stylesEntry, "utf8"), dirname(stylesEntry), stylesEntry);
  return `${HEADER}${css.trimEnd()}\n${grainTileRule()}`;
}

if (import.meta.main) {
  const output = await buildStyles();
  if (process.argv.includes("--stdout")) {
    process.stdout.write(output);
  } else {
    mkdirSync(dirname(stylesOutput), { recursive: true });
    writeFileSync(stylesOutput, output);
    console.log(`prism-react: wrote dist/styles.css (${output.length} bytes)`);
  }
}
