// The two catalogues the Apple showcase app reads (docs/showcase.md §1), and the key-path table the
// Apple binding tests read.
//
// Nothing in the app holds a list of tokens or of components. This module composes the readers the
// repository already has — the token manifest (`web/packages/tokens/src/generated/manifest.json`),
// the spec loader (`tools/spec/load.ts` through `tools/parity/specs.ts`) and the implementation
// manifest parser (`tools/parity/manifest.ts`) — and renders four Swift files:
//
//   Generated/DSTokenCatalog.swift      every token, with a `KeyPath<DSTokenSet, …>` per value kind
//   Generated/DSShowcaseCatalog.swift   every spec, its support row, its implemented version and its
//                                       examples with the props the spec writes
//   Generated/DSShowcaseBindings.swift  one renderer per component this build implements on Apple
//   DSComponentsTests/Generated/DSTokenKeyPaths.swift
//                                       every `sys` and `comp` token path → its `KeyPath<DSTokenSet, …>`,
//                                       so a binding test resolves the cell the spec writes
//
// The third is the anti-staleness mechanism of the app: it names `DS<Name>Renderer`, so the moment a
// component enters `DSComponentsManifest.implemented` the showcase target stops compiling until
// somebody writes that renderer. The app shell never changes.
//
// The fourth is the same idea one layer down, for the tests: the showcase app resolves a token path to a
// key path so it can print the value the running scene resolves, and a binding test needs exactly that
// lookup to ask whether the implementation returns the token its spec names. One table, two readers
// (`swift/Tests/DSComponentsTests/DSSpecBindings.swift`).
import { posix } from 'node:path';
import { parseManifest } from '../../parity/manifest.ts';
import { LAYER_MANIFEST, MANIFESTS, PLATFORMS, type Platform } from '../../parity/config.ts';
import { readSpecs, type SpecRow } from '../../parity/specs.ts';
import { aliasTarget } from '../../tokens/ir/naming.ts';
import { collectTokens } from '../../tokens/ir/references.ts';
import type { SourceReader } from '../../tokens/source/reader.ts';
import { swiftString } from '../../tokens/formats/swift/syntax.ts';
import { memberType, readTypeTable, type TypeTable } from './swift-types.ts';

/** Where the generated sources of the app go. */
export const GENERATED_ROOT = 'swift/Showcase/Sources/DSShowcase/Generated';
/** Where the generated key-path table goes: a source directory of the `DSComponentsTests` target. */
export const TESTS_GENERATED_ROOT = 'swift/Tests/DSComponentsTests/Generated';
/** The roots this generator owns, and nothing else; `generate.ts` hands them to the writer. */
export const GENERATED_ROOTS: readonly string[] = [GENERATED_ROOT, TESTS_GENERATED_ROOT];
/** The published token manifest, the one artefact that carries every token's Swift member. */
export const TOKEN_MANIFEST = 'web/packages/tokens/src/generated/manifest.json';
/** The component tier's own documents, read for the system token each `comp` token aliases. */
export const COMP_TOKENS_DIR = 'tokens/comp';
/** Read for the repository URL the app links specs, the gallery and the parity report with. */
export const TOKENS_PACKAGE = 'web/packages/tokens/package.json';
export const VERSION_FILE = 'VERSION';

export const BUILD_COMMAND = '`pnpm showcase:apple --generate`';

/** The Apple platform keys, in the order the app prints them. */
export const APPLE_PLATFORMS: readonly Platform[] = ['ios', 'ipados', 'macos', 'watchos'];

export interface OutputFile {
  readonly path: string;
  readonly contents: string;
}

export interface CatalogResult {
  readonly files: readonly OutputFile[];
  readonly problems: readonly string[];
}

interface ManifestToken {
  readonly path: string;
  readonly id: string;
  readonly tier: string;
  readonly type: string;
  readonly css: string | null;
  readonly cssVars: readonly string[];
  readonly swift: string | null;
  readonly asset: string | null;
  readonly description: string | null;
  readonly deprecated: string | null;
}

function header(sources: string): string {
  return `// Generated by tools/showcase/apple from ${sources}. Do not edit; run ${BUILD_COMMAND}.`;
}

function file(lines: readonly string[]): string {
  return `${lines.join('\n').replace(/[ \t]+$/gm, '')}\n`;
}

// ---------------------------------------------------------------------------------------------
// Tokens
// ---------------------------------------------------------------------------------------------

/** The group a token belongs to: the first path segment, which is the component name in `comp`. */
export function groupOf(token: ManifestToken): string {
  const segments = token.path.split('.');
  return (token.tier === 'sys' ? segments[0] : segments[1]) ?? token.tier;
}

/** A colour a row can print: the colorset the OS resolves, and the token it was reached through. */
interface ColorSource {
  /** The colorset's asset name, or null when nothing in the chain has one. */
  readonly asset: string | null;
  /** The public path of the system token a `comp` token aliases, or null when this token *is* the colorset. */
  readonly alias: string | null;
}

/**
 * The system token each `comp` token is a whole-value alias of, by token id.
 *
 * A `comp` colour has no colorset of its own — the component tier is *one whole-value alias of a
 * system token per component part* (ARCHITECTURE §5) — so `manifest.json` carries no `asset` for one
 * and the app had nothing to print but the words "aliased colorset" beside a swatch that was right.
 * The reference is in the tier's own documents (`"$value": "{sys.color.border.strong}"`), so the
 * generator reads it here with the same two readers the token pipeline uses, and a row prints the
 * target's value and names the target.
 *
 * Brands override `ref` only (`BRAND_OVERRIDABLE`, ADR-0020 §1), so an alias is the same for every
 * brand and can be resolved once, at generation time.
 */
export function compAliases(reader: SourceReader, problems: string[]): Map<string, string> {
  const out = new Map<string, string>();
  for (const entry of reader.list(COMP_TOKENS_DIR)) {
    if (entry.dir || !entry.name.endsWith('.tokens.json')) continue;
    const file = posix.join(COMP_TOKENS_DIR, entry.name);
    let tree: unknown;
    try {
      tree = JSON.parse(reader.readText(file));
    } catch {
      problems.push(`${file}: is not readable as JSON`);
      continue;
    }
    if (!isRecord(tree)) {
      problems.push(`${file}: is not a DTCG document`);
      continue;
    }
    for (const [id, node] of collectTokens(tree)) {
      const target = aliasTarget(node['$value']);
      if (target !== null) out.set(id.replace(/\.\$root$/, ''), target);
    }
  }
  return out;
}

/** A token id as the manifest writes ids, and as it writes public paths (`sys.` is not in a path). */
function manifestKeys(byId: Map<string, ManifestToken>, byPath: Map<string, ManifestToken>, id: string): ManifestToken | null {
  return byId.get(id) ?? byId.get(`${id}.$root`) ?? byPath.get(id.replace(/^sys\./, '')) ?? null;
}

/**
 * Where a colour token's painted value comes from: its own colorset, or the one it aliases, following
 * the chain a `comp` token may take through another `comp` token. An unresolvable chain is reported,
 * never guessed — the app would otherwise print a swatch beside a value that is not in it.
 */
function colorSource(
  token: ManifestToken,
  aliases: ReadonlyMap<string, string>,
  byId: Map<string, ManifestToken>,
  byPath: Map<string, ManifestToken>,
  problems: string[],
): ColorSource {
  if (token.asset !== null) return { asset: token.asset, alias: null };
  const seen = new Set<string>([token.id]);
  let current: ManifestToken = token;
  // Four hops is more than the tier allows; it is here so a cycle in the sources cannot hang a build.
  for (let hop = 0; hop < 4; hop += 1) {
    const target = aliases.get(current.id);
    if (target === undefined) break;
    const next = manifestKeys(byId, byPath, target);
    if (next === null) {
      problems.push(`${token.path}: aliases ${target}, which is not a token of the manifest`);
      return { asset: null, alias: null };
    }
    if (seen.has(next.id)) {
      problems.push(`${token.path}: its alias chain returns to ${next.path}`);
      return { asset: null, alias: null };
    }
    seen.add(next.id);
    if (next.asset !== null) return { asset: next.asset, alias: next.path };
    current = next;
  }
  problems.push(`${token.path}: no colorset behind it — nothing in its alias chain carries one`);
  return { asset: null, alias: null };
}

/** The Swift value expression for a member, or null when the type table does not know the member. */
function valueExpression(token: ManifestToken, table: TypeTable, colors: (t: ManifestToken) => ColorSource): string | null {
  const member = token.swift;
  if (member === null) return '.unavailable';

  const faces = /^DSBrand\.faces\[\.([A-Za-z]+)\]$/.exec(member);
  if (faces !== null) return `.fontFace(.${faces[1] ?? ''})`;

  const parts = member.split('.');
  const root = parts[0] ?? '';
  const chain = parts.slice(1);
  if (chain.length === 0) return null;

  // `DSColor.accent` is `DSTokenSet.color.accent`: the brand's colors hang off the token set.
  const keyPathChain = root === 'DSColor' ? ['color', ...chain] : chain;
  const lookup = memberType(table, root === 'DSColor' ? 'DSColor' : 'DSTokenSet', chain);
  if (lookup === null) return null;
  const keyPath = `\\.${keyPathChain.join('.')}`;

  switch (lookup.type) {
    case 'CGFloat':
      return `.dimension(${keyPath})`;
    case 'Double':
      return `.number(${keyPath})`;
    case 'TimeInterval':
      return `.duration(${keyPath})`;
    case 'Bool':
      return `.flag(${keyPath})`;
    case 'Color': {
      const source = colors(token);
      const asset = source.asset === null ? 'nil' : `DSColorToken(rawValue: ${swiftString(source.asset)})`;
      return `.color(${keyPath}, ${asset}, ${optionalString(source.alias)})`;
    }
    case 'DSTypeRole': {
      // A type role is rendered with `dsText(_:)`, which takes a key path into `DSTokenSet.Typography`.
      const inner = keyPathChain.slice(1).join('.');
      return keyPathChain[0] === 'typography' ? `.typography(\\.${inner})` : null;
    }
    case 'DSShadowToken':
      return `.shadow(${keyPath})`;
    case 'DSGradientToken':
      return `.gradient(${keyPath})`;
    case 'DSSpringToken':
      return `.spring(${keyPath})`;
    case 'DSCubicBezier':
      return `.easing(${keyPath})`;
    case 'DSStrokeStyle':
      return `.stroke(${keyPath})`;
    default:
      return null;
  }
}

/** A Swift identifier for a group's array: `sysColor`, `refBlur`, `compAreaChart`. */
function groupSymbol(tier: string, group: string): string {
  const words = group.split(/[-.]/).filter((w) => w !== '');
  const camel = words.map((w, i) => (i === 0 ? w : w.charAt(0).toUpperCase() + w.slice(1))).join('');
  return `${tier}${camel.charAt(0).toUpperCase()}${camel.slice(1)}`;
}

function optionalString(value: string | null): string {
  return value === null || value === '' ? 'nil' : swiftString(value);
}

export function renderTokenCatalog(reader: SourceReader, problems: string[]): OutputFile {
  const manifest = JSON.parse(reader.readText(TOKEN_MANIFEST)) as { tokens: ManifestToken[] };
  const table = readTypeTable(reader);
  const version = reader.readText(VERSION_FILE).trim();
  const byId = new Map(manifest.tokens.map((t) => [t.id, t] as const));
  const byPath = new Map(manifest.tokens.map((t) => [t.path, t] as const));
  const aliases = compAliases(reader, problems);
  const colors = (token: ManifestToken): ColorSource => colorSource(token, aliases, byId, byPath, problems);

  const byGroup = new Map<string, ManifestToken[]>();
  for (const token of manifest.tokens) {
    const key = `${token.tier}\u0000${groupOf(token)}`;
    const list = byGroup.get(key);
    if (list === undefined) byGroup.set(key, [token]);
    else list.push(token);
  }

  // Sections, biggest first inside a tier: the app's Foundations order is the data's own shape.
  const order = ['sys', 'comp', 'ref'];
  const groups = [...byGroup.entries()]
    .map(([key, tokens]) => {
      const [tier = '', group = ''] = key.split('\u0000');
      return { tier, group, tokens };
    })
    .sort((a, b) =>
      order.indexOf(a.tier) - order.indexOf(b.tier) ||
      b.tokens.length - a.tokens.length ||
      (a.group < b.group ? -1 : a.group > b.group ? 1 : 0),
    );

  const lines: string[] = [
    header(`${TOKEN_MANIFEST} and swift/Sources/DSTokens/Generated`),
    '//',
    '// One entry per token of the manifest. `value` carries a KeyPath into `DSTokenSet`, so the app shows the',
    '// value the running scene resolves and never a literal; a `ref` primitive has no Swift API and says so.',
    'import SwiftUI',
    'import DSTokens',
    '',
    'extension DSTokenCatalog {',
    `    /// The system version the tokens were built at (\`VERSION\`).`,
    `    public static let version = ${swiftString(version)}`,
    '',
  ];

  for (const { tier, group, tokens } of groups) {
    const symbol = groupSymbol(tier, group);
    lines.push(`    static let ${symbol}: [DSTokenCatalogEntry] = [`);
    for (const token of tokens) {
      const value = valueExpression(token, table, colors);
      if (value === null) {
        problems.push(`${token.path}: no Swift member type for ${token.swift ?? '(none)'} — the token catalogue is stale`);
        continue;
      }
      const css = token.css ?? token.cssVars[0] ?? null;
      lines.push(
        `        DSTokenCatalogEntry(` +
          `path: ${swiftString(token.path)}, ` +
          `id: ${swiftString(token.id)}, ` +
          `tier: .${tier}, ` +
          `group: ${swiftString(group)}, ` +
          `type: ${swiftString(token.type)}, ` +
          `swiftMember: ${optionalString(token.swift)}, ` +
          `cssVariable: ${optionalString(css)}, ` +
          `summary: ${optionalString(token.description)}, ` +
          `deprecated: ${optionalString(token.deprecated)}, ` +
          `value: ${value}),`,
      );
    }
    lines.push('    ]', '');
  }

  lines.push('    /// Every group, in the order the Foundations screen lists them.');
  lines.push('    public static let groups: [DSTokenGroup] = [');
  for (const { tier, group, tokens } of groups) {
    lines.push(
      `        DSTokenGroup(tier: .${tier}, name: ${swiftString(group)}, count: ${tokens.length}, entries: ${groupSymbol(tier, group)}),`,
    );
  }
  lines.push('    ]', '}');
  return { path: posix.join(GENERATED_ROOT, 'DSTokenCatalog.swift'), contents: file(lines) };
}

// ---------------------------------------------------------------------------------------------
// Token key paths (the Apple binding tests)
// ---------------------------------------------------------------------------------------------

/** One dictionary of the generated key-path file. */
interface KeyPathTable {
  /** The dictionary's name in `DSTokenKeyPaths`. */
  readonly name: string;
  /** The key path's root type, as Swift writes it. */
  readonly root: string;
  /** The key path's value type, as Swift writes it. */
  readonly value: string;
  /** The member chain the key path is rooted at, and therefore drops: `['typography']` for the roles. */
  readonly under?: readonly string[];
  /** The line above the table. */
  readonly doc: string;
  /** How a failure names this kind: "…, which the catalogue binds as a dimension". */
  readonly noun: string;
}

/** The tables, in the order the file writes them, which is the order a failure searches them in. */
const KEY_PATH_TABLES: readonly KeyPathTable[] = [
  { name: 'color', root: 'DSTokenSet', value: 'Color', noun: 'a colour', doc: 'Every colour: `color.bg.page` is `\\DSTokenSet.color.bgPage`.' },
  { name: 'dimension', root: 'DSTokenSet', value: 'CGFloat', noun: 'a dimension', doc: 'Every dimension, in points.' },
  { name: 'number', root: 'DSTokenSet', value: 'Double', noun: 'a number', doc: 'Every unitless number, and every duration in seconds.' },
  {
    name: 'typography',
    root: 'DSTokenSet.Typography',
    value: 'DSTypeRole',
    under: ['typography'],
    noun: 'a type role',
    doc: 'Every type role, rooted where `DSTextRole.keyPath` is rooted, so the two compare directly.',
  },
  { name: 'shadow', root: 'DSTokenSet', value: 'DSShadowToken', noun: 'a shadow', doc: 'Every shadow (the elevation levels).' },
  { name: 'gradient', root: 'DSTokenSet', value: 'DSGradientToken', noun: 'a gradient', doc: 'Every gradient.' },
  { name: 'spring', root: 'DSTokenSet', value: 'DSSpringToken', noun: 'a spring', doc: 'Every spring, which is what a `motion` block binds.' },
  { name: 'easing', root: 'DSTokenSet', value: 'DSCubicBezier', noun: 'an easing curve', doc: 'Every easing curve.' },
  { name: 'stroke', root: 'DSTokenSet', value: 'DSStrokeStyle', noun: 'a stroke style', doc: 'Every stroke style (the dash grammar of the chart tier).' },
  { name: 'flag', root: 'DSTokenSet', value: 'Bool', noun: 'a flag', doc: 'Every flag (the interaction axes components read).' },
];

/**
 * The Swift member type of a token → the table its key path goes in. A `sys` or `comp` token whose type
 * is not here is reported, not skipped: the table would otherwise silently stop covering a token a spec
 * may bind, and the binding test would then say "not a token the catalogue binds" about a token that is.
 *
 * `TimeInterval` is `Double`, so durations share the number table; the seconds are in the token's name.
 */
const KEY_PATH_KINDS: Readonly<Record<string, string>> = {
  Color: 'color',
  CGFloat: 'dimension',
  Double: 'number',
  TimeInterval: 'number',
  DSTypeRole: 'typography',
  DSShadowToken: 'shadow',
  DSGradientToken: 'gradient',
  DSSpringToken: 'spring',
  DSCubicBezier: 'easing',
  DSStrokeStyle: 'stroke',
  Bool: 'flag',
};

/** A font face (`DSBrand.faces[.body]`) is not a key path into the token set, and no spec binds one. */
const FONT_FACE = /^DSBrand\.faces\[\./;

interface KeyPathRow {
  readonly path: string;
  readonly keyPath: string;
}

/**
 * Every `sys` and `comp` token as the key path that reads its value out of a `DSTokenSet`, grouped by
 * the table it belongs to and sorted by token path.
 *
 * `ref` primitives are left out: they have no Swift API (`DSTokenCatalog` renders them `.unavailable`)
 * and a spec never binds one (ADR-0024 §5).
 */
function keyPathRows(reader: SourceReader, problems: string[]): Map<string, KeyPathRow[]> {
  const manifest = JSON.parse(reader.readText(TOKEN_MANIFEST)) as { tokens: ManifestToken[] };
  const table = readTypeTable(reader);
  const rows = new Map<string, KeyPathRow[]>();
  const owners = new Map<string, string>();
  for (const token of manifest.tokens) {
    if (token.tier === 'ref') continue;
    const member = token.swift;
    if (member === null || FONT_FACE.test(member)) continue;
    const parts = member.split('.');
    const root = parts[0] ?? '';
    const chain = parts.slice(1);
    if (chain.length === 0) continue;
    const lookup = memberType(table, root === 'DSColor' ? 'DSColor' : 'DSTokenSet', chain);
    if (lookup === null) {
      problems.push(`${token.path}: no Swift member type for ${member} — the key-path table is stale`);
      continue;
    }
    const name = KEY_PATH_KINDS[lookup.type];
    const kind = KEY_PATH_TABLES.find((t) => t.name === name);
    if (kind === undefined) {
      problems.push(`${token.path}: ${lookup.type} is not a value kind the key-path table carries`);
      continue;
    }
    // `DSColor.accent` is `DSTokenSet.color.accent`: the brand's colors hang off the token set.
    const full = root === 'DSColor' ? ['color', ...chain] : chain;
    const under = kind.under ?? [];
    const steps = full.slice(under.length);
    // A rooted table (`typography`) takes only members that live under that root; a `DSTypeRole` reached
    // any other way would be a key path this table's type cannot hold.
    if (steps.length === 0 || under.some((step, i) => full[i] !== step)) {
      problems.push(`${token.path}: ${member} is not under the ${kind.root} the ${kind.name} table is rooted at`);
      continue;
    }
    const owner = owners.get(member);
    if (owner !== undefined) {
      problems.push(`${token.path}: shares the Swift member ${member} with ${owner}, so one key path names two tokens`);
      continue;
    }
    owners.set(member, token.path);
    const list = rows.get(kind.name);
    const entry = { path: token.path, keyPath: `\\.${steps.join('.')}` };
    if (list === undefined) rows.set(kind.name, [entry]);
    else list.push(entry);
  }
  for (const list of rows.values()) list.sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
  return rows;
}

export function renderTokenKeyPaths(reader: SourceReader, problems: string[]): OutputFile {
  const rows = keyPathRows(reader, problems);
  const lines: string[] = [
    header(`${TOKEN_MANIFEST} and swift/Sources/DSTokens/Generated`),
    '//',
    '// One entry per `sys` and `comp` token: the path a spec binds → the key path that reads its value out of a',
    '// `DSTokenSet`. `DSSpecBindings` turns the cell of `spec/components/<Name>.yaml` into the key path the',
    '// implementation must return, so the binding matrix is written down once, in the spec, and the Apple',
    '// assertion is the sentence the web one already says (`web/packages/react/test/button.test.tsx`).',
    '//',
    '// `ref` primitives are not here: they have no Swift API and no spec binds one (ADR-0024 §5). Neither are',
    '// the font faces, which reach a component through `type.*` and are not a key path into the token set.',
    '//',
    '// The tables are `nonisolated(unsafe)` because the standard library does not conform `KeyPath` to',
    '// `Sendable` (`DSTextRoles` says the same). They are immutable `let`s, initialized once; the annotation',
    '// is what keeps them readable from a parameterized `@Test`, whose arguments are evaluated off the main',
    '// actor while this target is `MainActor` by default.',
    'import SwiftUI',
    'import DSTokens',
    '',
    'nonisolated enum DSTokenKeyPaths {',
  ];
  for (const kind of KEY_PATH_TABLES) {
    const list = rows.get(kind.name) ?? [];
    if (list.length === 0) {
      problems.push(`${kind.name}: no token resolves to this table — the key-path table is stale`);
      continue;
    }
    lines.push(`    /// ${kind.doc} (${list.length} tokens.)`);
    lines.push(`    nonisolated(unsafe) static let ${kind.name}: [String: KeyPath<${kind.root}, ${kind.value}>] = [`);
    for (const row of list) lines.push(`        ${swiftString(row.path)}: ${row.keyPath},`);
    lines.push('    ]', '');
  }
  lines.push(
    '    /// What the catalogue binds a token path as, for the failure that says a cell is of another kind.',
    '    static func kind(of path: String) -> String? {',
    ...KEY_PATH_TABLES.map((kind) => `        if ${kind.name}[path] != nil { return ${swiftString(kind.noun)} }`),
    '        return nil',
    '    }',
    '}',
  );
  return { path: posix.join(TESTS_GENERATED_ROOT, 'DSTokenKeyPaths.swift'), contents: file(lines) };
}

// ---------------------------------------------------------------------------------------------
// Components
// ---------------------------------------------------------------------------------------------

interface SpecExample {
  readonly id: string;
  readonly props: readonly (readonly [string, unknown])[];
  readonly surface: string | null;
  readonly backdrop: string | null;
  readonly grid: readonly string[];
  readonly schemes: readonly string[];
  readonly description: string | null;
}

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v);
}

function propValue(value: unknown): string {
  if (typeof value === 'string') return `.string(${swiftString(value)})`;
  if (typeof value === 'number') return `.number(${Number.isInteger(value) ? `${value}` : `${value}`})`;
  if (typeof value === 'boolean') return `.bool(${value ? 'true' : 'false'})`;
  if (Array.isArray(value)) return `.list([${value.map(propValue).join(', ')}])`;
  if (isRecord(value)) {
    const pairs = Object.entries(value).map(([k, v]) => `DSPropValue.Pair(${swiftString(k)}, ${propValue(v)})`);
    return `.map([${pairs.join(', ')}])`;
  }
  return '.unknown';
}

/** The spec's props of `type: action`, which a harness must stage with a handler (see `actionsOf`). */
function actionPropsOf(spec: SpecRow): string[] {
  const raw = spec.doc.value?.['props'];
  if (!Array.isArray(raw)) return [];
  const names: string[] = [];
  for (const item of raw) {
    if (!isRecord(item)) continue;
    if (item['type'] !== 'action') continue;
    const name = item['name'];
    if (typeof name === 'string') names.push(name);
  }
  return names;
}

function examplesOf(spec: SpecRow): SpecExample[] {
  const raw = spec.doc.value?.['examples'];
  if (!Array.isArray(raw)) return [];
  const out: SpecExample[] = [];
  for (const item of raw) {
    if (!isRecord(item)) continue;
    const id = item['id'];
    if (typeof id !== 'string') continue;
    const props = isRecord(item['props']) ? Object.entries(item['props']) : [];
    const grid = Array.isArray(item['grid']) ? item['grid'].filter((g): g is string => typeof g === 'string') : [];
    const schemes = Array.isArray(item['schemes'])
      ? item['schemes'].filter((s): s is string => typeof s === 'string')
      : ['light', 'dark'];
    out.push({
      id,
      props,
      surface: typeof item['surface'] === 'string' ? item['surface'] : null,
      backdrop: typeof item['backdrop'] === 'string' ? item['backdrop'] : null,
      grid,
      schemes,
      description: typeof item['description'] === 'string' ? item['description'] : null,
    });
  }
  return out;
}

/**
 * `notes.platform`, one note per spec platform key. A key that is not one of them is a problem, not a
 * note to skip: the schema rejects it too (spec/component.schema.json), and a misspelt `watchos` dropped
 * here would take its note out of the app without a word.
 */
function platformNotesOf(spec: SpecRow, problems: string[]): readonly (readonly [string, string])[] {
  const notes = spec.doc.value?.['notes'];
  if (!isRecord(notes)) return [];
  const platform = notes['platform'];
  if (!isRecord(platform)) return [];
  const out: [string, string][] = [];
  for (const [key, value] of Object.entries(platform)) {
    if (!(PLATFORMS as readonly string[]).includes(key)) {
      problems.push(`${spec.file}: notes.platform.${key} is not a spec platform key (${PLATFORMS.join(', ')})`);
    } else if (typeof value === 'string') {
      out.push([key, value]);
    }
  }
  return out;
}

function stringField(spec: SpecRow, field: string): string | null {
  const value = spec.doc.value?.[field];
  return typeof value === 'string' ? value.trim() : null;
}

/** `implemented` of the two Swift manifests, keyed by component name → platform → version. */
export function appleImplemented(reader: SourceReader, problems: string[]): Map<string, Map<string, number>> {
  const out = new Map<string, Map<string, number>>();
  for (const manifest of MANIFESTS) {
    if (manifest.stack !== 'swiftui') continue;
    if (!reader.exists(manifest.path)) {
      problems.push(`${manifest.path} is missing`);
      continue;
    }
    const parsed = parseManifest(reader.readText(manifest.path), manifest.syntax);
    for (const problem of parsed.problems) problems.push(`${manifest.path}:${problem.line} ${problem.message}`);
    for (const entry of parsed.entries) {
      const versions = out.get(entry.name) ?? new Map<string, number>();
      for (const version of entry.versions) versions.set(version.platform, version.version);
      out.set(entry.name, versions);
    }
  }
  return out;
}

export interface ComponentCatalog {
  readonly catalog: OutputFile;
  readonly bindings: OutputFile;
  /** The components this build implements on at least one Apple platform, in spec order. */
  readonly implementedNames: readonly string[];
}

function repositoryUrl(reader: SourceReader): string {
  const pkg = JSON.parse(reader.readText(TOKENS_PACKAGE)) as { repository?: { url?: string } };
  const url = pkg.repository?.url ?? '';
  return url.replace(/^git\+/, '').replace(/\.git$/, '');
}

export function renderComponentCatalog(reader: SourceReader, problems: string[]): ComponentCatalog {
  const { specs, diagnostics } = readSpecs(reader);
  for (const d of diagnostics) problems.push(`${d.file ?? '?'}: ${d.message}`);
  const implemented = appleImplemented(reader, problems);

  const lines: string[] = [
    header('spec/components, spec/patterns and the Swift implementation manifests'),
    '//',
    '// Every spec is a row, implemented or not, so the app can never silently omit one: the support level',
    '// comes from the spec, the implemented version from `DSComponentsManifest`/`DSChartsManifest`, and the',
    '// examples are the spec\'s own `examples[]` with the props as the spec writes them.',
    'import SwiftUI',
    '',
    'extension DSShowcaseCatalog {',
    `    /// Where the app links a spec, the gallery and the parity report.`,
    `    public static let repositoryURL = ${swiftString(repositoryUrl(reader))}`,
    '',
  ];

  const implementedNames: string[] = [];
  const entryLines: string[] = [];
  for (const spec of specs) {
    const versions = implemented.get(spec.name) ?? new Map<string, number>();
    const apple = APPLE_PLATFORMS.filter((p) => versions.has(p));
    const isPattern = LAYER_MANIFEST[spec.layer] === null;
    if (apple.length > 0 && !isPattern) implementedNames.push(spec.name);
    const platforms = [...spec.platforms.entries()].map(([p, s]) => `(${swiftString(p)}, .${s})`);
    const implementedPairs = apple.map((p) => `(${swiftString(p)}, ${versions.get(p) ?? 0})`);
    const examples = examplesOf(spec);
    // Every `type: action` prop of the spec. The web harness injects a no-op for each of these
    // (`web/apps/showcase/src/sections/Components.tsx`); Apple stages them through
    // `DSSpecExample.handler(_:)`, so a Card example draws the open glyph its baseline shows
    // (Card.yaml behavior 4) instead of silently staging an unpressable card.
    const actionProps = actionPropsOf(spec);
    lines.push(
      `    static let spec${spec.name}: DSComponentEntry = DSComponentEntry(`,
      `            name: ${swiftString(spec.name)},`,
      `            layer: ${swiftString(spec.layer)},`,
      `            summary: ${swiftString(stringField(spec, 'summary') ?? '')},`,
      `            since: ${optionalString(stringField(spec, 'since'))},`,
      `            specVersion: ${spec.specVersion},`,
      `            specPath: ${swiftString(spec.file)},`,
      `            isPattern: ${isPattern ? 'true' : 'false'},`,
      `            platforms: [${platforms.join(', ')}],`,
      `            implemented: [${implementedPairs.join(', ')}],`,
      `            platformNotes: [${platformNotesOf(spec, problems).map(([k, v]) => `(${swiftString(k)}, ${swiftString(v)})`).join(', ')}],`,
      '            examples: [',
    );
    for (const example of examples) {
      const props = example.props.map(([k, v]) => `(${swiftString(k)}, ${propValue(v)})`);
      lines.push(
        `                DSSpecExample(` +
          `id: ${swiftString(example.id)}, ` +
          `props: [${props.join(', ')}], ` +
          `surface: ${optionalString(example.surface)}, ` +
          `backdrop: ${optionalString(example.backdrop)}, ` +
          `grid: [${example.grid.map(swiftString).join(', ')}], ` +
          `schemes: [${example.schemes.map(swiftString).join(', ')}], ` +
          `actions: [${actionProps.map(swiftString).join(', ')}], ` +
          `summary: ${optionalString(example.description)}),`,
      );
    }
    lines.push('            ]', '    )', '');
    entryLines.push(`        spec${spec.name},`);
  }
  lines.push('    public static let components: [DSComponentEntry] = [', ...entryLines, '    ]', '}');

  const bindingLines: string[] = [
    header('the Swift implementation manifests'),
    '//',
    '// One renderer per component this build implements on Apple. A component that lands in',
    '// `DSComponentsManifest.implemented` appears here on the next generate, and `DSShowcase` then does not',
    '// compile until `DS<Name>Renderer` exists — which is how the showcase cannot go stale without saying so.',
    'import SwiftUI',
    '',
    'extension DSShowcaseRenderers {',
    '    static let generated: [String: any DSExampleRenderer] = [',
    ...implementedNames.map((name) => `        ${swiftString(name)}: DS${name}Renderer(),`),
    '    ]',
    '}',
  ];

  return {
    catalog: { path: posix.join(GENERATED_ROOT, 'DSShowcaseCatalog.swift'), contents: file(lines) },
    bindings: { path: posix.join(GENERATED_ROOT, 'DSShowcaseBindings.swift'), contents: file(bindingLines) },
    implementedNames,
  };
}

/** Both catalogues, the renderer bindings and the key-path table, as the files a build would write. */
export function renderCatalogs(reader: SourceReader): CatalogResult {
  const problems: string[] = [];
  const tokens = renderTokenCatalog(reader, problems);
  const keyPaths = renderTokenKeyPaths(reader, problems);
  const components = renderComponentCatalog(reader, problems);
  const files = [tokens, keyPaths, components.catalog, components.bindings].sort((a, b) => (a.path < b.path ? -1 : 1));
  return { files, problems };
}
