// The two catalogues the Apple showcase app reads (docs/showcase.md §1).
//
// Nothing in the app holds a list of tokens or of components. This module composes the readers the
// repository already has — the token manifest (`web/packages/tokens/src/generated/manifest.json`),
// the spec loader (`tools/spec/load.ts` through `tools/parity/specs.ts`) and the implementation
// manifest parser (`tools/parity/manifest.ts`) — and renders three Swift files:
//
//   Generated/DSTokenCatalog.swift      every token, with a `KeyPath<DSTokenSet, …>` per value kind
//   Generated/DSShowcaseCatalog.swift   every spec, its support row, its implemented version and its
//                                       examples with the props the spec writes
//   Generated/DSShowcaseBindings.swift  one renderer per component this build implements on Apple
//
// The last one is the anti-staleness mechanism: it names `DS<Name>Renderer`, so the moment a
// component enters `DSComponentsManifest.implemented` the showcase target stops compiling until
// somebody writes that renderer. The app shell never changes.
import { posix } from 'node:path';
import { parseManifest } from '../../parity/manifest.ts';
import { LAYER_MANIFEST, MANIFESTS, PLATFORMS, type Platform } from '../../parity/config.ts';
import { readSpecs, type SpecRow } from '../../parity/specs.ts';
import { aliasTarget } from '../../tokens/ir/naming.ts';
import { collectTokens } from '../../tokens/ir/references.ts';
import type { SourceReader } from '../../tokens/source/reader.ts';
import { swiftString } from '../../tokens/formats/swift/syntax.ts';
import { memberType, readTypeTable, type TypeTable } from './swift-types.ts';

/** Where the generated sources go; the showcase generator owns this root and nothing else. */
export const GENERATED_ROOT = 'swift/Showcase/Sources/DSShowcase/Generated';
/** The published token manifest, the one artefact that carries every token's Swift member. */
export const TOKEN_MANIFEST = 'web/packages/tokens/src/generated/manifest.json';
/** The component tier's own documents, read for the system token each `comp` token aliases. */
export const COMP_TOKENS_DIR = 'tokens/comp';
/** Read for the repository URL the app links specs, the gallery and the parity report with. */
export const TOKENS_PACKAGE = 'web/packages/tokens/package.json';
export const VERSION_FILE = 'VERSION';

export const BUILD_COMMAND = '`pnpm showcase:apple --generate`';

/** The Apple platform keys, in the order the app prints them. */
export const APPLE_PLATFORMS: readonly Platform[] = ['ios', 'ipados', 'macos', 'watchos'];

export interface OutputFile {
  readonly path: string;
  readonly contents: string;
}

export interface CatalogResult {
  readonly files: readonly OutputFile[];
  readonly problems: readonly string[];
}

interface ManifestToken {
  readonly path: string;
  readonly id: string;
  readonly tier: string;
  readonly type: string;
  readonly css: string | null;
  readonly cssVars: readonly string[];
  readonly swift: string | null;
  readonly asset: string | null;
  readonly description: string | null;
  readonly deprecated: string | null;
}

function header(sources: string): string {
  return `// Generated by tools/showcase/apple from ${sources}. Do not edit; run ${BUILD_COMMAND}.`;
}

function file(lines: readonly string[]): string {
  return `${lines.join('\n').replace(/[ \t]+$/gm, '')}\n`;
}

// ---------------------------------------------------------------------------------------------
// Tokens
// ---------------------------------------------------------------------------------------------

/** The group a token belongs to: the first path segment, which is the component name in `comp`. */
export function groupOf(token: ManifestToken): string {
  const segments = token.path.split('.');
  return (token.tier === 'sys' ? segments[0] : segments[1]) ?? token.tier;
}

/** A colour a row can print: the colorset the OS resolves, and the token it was reached through. */
interface ColorSource {
  /** The colorset's asset name, or null when nothing in the chain has one. */
  readonly asset: string | null;
  /** The public path of the system token a `comp` token aliases, or null when this token *is* the colorset. */
  readonly alias: string | null;
}

/**
 * The system token each `comp` token is a whole-value alias of, by token id.
 *
 * A `comp` colour has no colorset of its own — the component tier is *one whole-value alias of a
 * system token per component part* (ARCHITECTURE §5) — so `manifest.json` carries no `asset` for one
 * and the app had nothing to print but the words "aliased colorset" beside a swatch that was right.
 * The reference is in the tier's own documents (`"$value": "{sys.color.border.strong}"`), so the
 * generator reads it here with the same two readers the token pipeline uses, and a row prints the
 * target's value and names the target.
 *
 * Brands override `ref` only (`BRAND_OVERRIDABLE`, ADR-0020 §1), so an alias is the same for every
 * brand and can be resolved once, at generation time.
 */
export function compAliases(reader: SourceReader, problems: string[]): Map<string, string> {
  const out = new Map<string, string>();
  for (const entry of reader.list(COMP_TOKENS_DIR)) {
    if (entry.dir || !entry.name.endsWith('.tokens.json')) continue;
    const file = posix.join(COMP_TOKENS_DIR, entry.name);
    let tree: unknown;
    try {
      tree = JSON.parse(reader.readText(file));
    } catch {
      problems.push(`${file}: is not readable as JSON`);
      continue;
    }
    if (!isRecord(tree)) {
      problems.push(`${file}: is not a DTCG document`);
      continue;
    }
    for (const [id, node] of collectTokens(tree)) {
      const target = aliasTarget(node['$value']);
      if (target !== null) out.set(id.replace(/\.\$root$/, ''), target);
    }
  }
  return out;
}

/** A token id as the manifest writes ids, and as it writes public paths (`sys.` is not in a path). */
function manifestKeys(byId: Map<string, ManifestToken>, byPath: Map<string, ManifestToken>, id: string): ManifestToken | null {
  return byId.get(id) ?? byId.get(`${id}.$root`) ?? byPath.get(id.replace(/^sys\./, '')) ?? null;
}

/**
 * Where a colour token's painted value comes from: its own colorset, or the one it aliases, following
 * the chain a `comp` token may take through another `comp` token. An unresolvable chain is reported,
 * never guessed — the app would otherwise print a swatch beside a value that is not in it.
 */
function colorSource(
  token: ManifestToken,
  aliases: ReadonlyMap<string, string>,
  byId: Map<string, ManifestToken>,
  byPath: Map<string, ManifestToken>,
  problems: string[],
): ColorSource {
  if (token.asset !== null) return { asset: token.asset, alias: null };
  const seen = new Set<string>([token.id]);
  let current: ManifestToken = token;
  // Four hops is more than the tier allows; it is here so a cycle in the sources cannot hang a build.
  for (let hop = 0; hop < 4; hop += 1) {
    const target = aliases.get(current.id);
    if (target === undefined) break;
    const next = manifestKeys(byId, byPath, target);
    if (next === null) {
      problems.push(`${token.path}: aliases ${target}, which is not a token of the manifest`);
      return { asset: null, alias: null };
    }
    if (seen.has(next.id)) {
      problems.push(`${token.path}: its alias chain returns to ${next.path}`);
      return { asset: null, alias: null };
    }
    seen.add(next.id);
    if (next.asset !== null) return { asset: next.asset, alias: next.path };
    current = next;
  }
  problems.push(`${token.path}: no colorset behind it — nothing in its alias chain carries one`);
  return { asset: null, alias: null };
}

/** The Swift value expression for a member, or null when the type table does not know the member. */
function valueExpression(token: ManifestToken, table: TypeTable, colors: (t: ManifestToken) => ColorSource): string | null {
  const member = token.swift;
  if (member === null) return '.unavailable';

  const faces = /^DSBrand\.faces\[\.([A-Za-z]+)\]$/.exec(member);
  if (faces !== null) return `.fontFace(.${faces[1] ?? ''})`;

  const parts = member.split('.');
  const root = parts[0] ?? '';
  const chain = parts.slice(1);
  if (chain.length === 0) return null;

  // `DSColor.accent` is `DSTokenSet.color.accent`: the brand's colors hang off the token set.
  const keyPathChain = root === 'DSColor' ? ['color', ...chain] : chain;
  const lookup = memberType(table, root === 'DSColor' ? 'DSColor' : 'DSTokenSet', chain);
  if (lookup === null) return null;
  const keyPath = `\\.${keyPathChain.join('.')}`;

  switch (lookup.type) {
    case 'CGFloat':
      return `.dimension(${keyPath})`;
    case 'Double':
      return `.number(${keyPath})`;
    case 'TimeInterval':
      return `.duration(${keyPath})`;
    case 'Bool':
      return `.flag(${keyPath})`;
    case 'Color': {
      const source = colors(token);
      const asset = source.asset === null ? 'nil' : `DSColorToken(rawValue: ${swiftString(source.asset)})`;
      return `.color(${keyPath}, ${asset}, ${optionalString(source.alias)})`;
    }
    case 'DSTypeRole': {
      // A type role is rendered with `dsText(_:)`, which takes a key path into `DSTokenSet.Typography`.
      const inner = keyPathChain.slice(1).join('.');
      return keyPathChain[0] === 'typography' ? `.typography(\\.${inner})` : null;
    }
    case 'DSShadowToken':
      return `.shadow(${keyPath})`;
    case 'DSGradientToken':
      return `.gradient(${keyPath})`;
    case 'DSSpringToken':
      return `.spring(${keyPath})`;
    case 'DSCubicBezier':
      return `.easing(${keyPath})`;
    case 'DSStrokeStyle':
      return `.stroke(${keyPath})`;
    default:
      return null;
  }
}

/** A Swift identifier for a group's array: `sysColor`, `refBlur`, `compAreaChart`. */
function groupSymbol(tier: string, group: string): string {
  const words = group.split(/[-.]/).filter((w) => w !== '');
  const camel = words.map((w, i) => (i === 0 ? w : w.charAt(0).toUpperCase() + w.slice(1))).join('');
  return `${tier}${camel.charAt(0).toUpperCase()}${camel.slice(1)}`;
}

function optionalString(value: string | null): string {
  return value === null || value === '' ? 'nil' : swiftString(value);
}

export function renderTokenCatalog(reader: SourceReader, problems: string[]): OutputFile {
  const manifest = JSON.parse(reader.readText(TOKEN_MANIFEST)) as { tokens: ManifestToken[] };
  const table = readTypeTable(reader);
  const version = reader.readText(VERSION_FILE).trim();
  const byId = new Map(manifest.tokens.map((t) => [t.id, t] as const));
  const byPath = new Map(manifest.tokens.map((t) => [t.path, t] as const));
  const aliases = compAliases(reader, problems);
  const colors = (token: ManifestToken): ColorSource => colorSource(token, aliases, byId, byPath, problems);

  const byGroup = new Map<string, ManifestToken[]>();
  for (const token of manifest.tokens) {
    const key = `${token.tier}\u0000${groupOf(token)}`;
    const list = byGroup.get(key);
    if (list === undefined) byGroup.set(key, [token]);
    else list.push(token);
  }

  // Sections, biggest first inside a tier: the app's Foundations order is the data's own shape.
  const order = ['sys', 'comp', 'ref'];
  const groups = [...byGroup.entries()]
    .map(([key, tokens]) => {
      const [tier = '', group = ''] = key.split('\u0000');
      return { tier, group, tokens };
    })
    .sort((a, b) =>
      order.indexOf(a.tier) - order.indexOf(b.tier) ||
      b.tokens.length - a.tokens.length ||
      (a.group < b.group ? -1 : a.group > b.group ? 1 : 0),
    );

  const lines: string[] = [
    header(`${TOKEN_MANIFEST} and swift/Sources/DSTokens/Generated`),
    '//',
    '// One entry per token of the manifest. `value` carries a KeyPath into `DSTokenSet`, so the app shows the',
    '// value the running scene resolves and never a literal; a `ref` primitive has no Swift API and says so.',
    'import SwiftUI',
    'import DSTokens',
    '',
    'extension DSTokenCatalog {',
    `    /// The system version the tokens were built at (\`VERSION\`).`,
    `    public static let version = ${swiftString(version)}`,
    '',
  ];

  for (const { tier, group, tokens } of groups) {
    const symbol = groupSymbol(tier, group);
    lines.push(`    static let ${symbol}: [DSTokenCatalogEntry] = [`);
    for (const token of tokens) {
      const value = valueExpression(token, table, colors);
      if (value === null) {
        problems.push(`${token.path}: no Swift member type for ${token.swift ?? '(none)'} — the token catalogue is stale`);
        continue;
      }
      const css = token.css ?? token.cssVars[0] ?? null;
      lines.push(
        `        DSTokenCatalogEntry(` +
          `path: ${swiftString(token.path)}, ` +
          `id: ${swiftString(token.id)}, ` +
          `tier: .${tier}, ` +
          `group: ${swiftString(group)}, ` +
          `type: ${swiftString(token.type)}, ` +
          `swiftMember: ${optionalString(token.swift)}, ` +
          `cssVariable: ${optionalString(css)}, ` +
          `summary: ${optionalString(token.description)}, ` +
          `deprecated: ${optionalString(token.deprecated)}, ` +
          `value: ${value}),`,
      );
    }
    lines.push('    ]', '');
  }

  lines.push('    /// Every group, in the order the Foundations screen lists them.');
  lines.push('    public static let groups: [DSTokenGroup] = [');
  for (const { tier, group, tokens } of groups) {
    lines.push(
      `        DSTokenGroup(tier: .${tier}, name: ${swiftString(group)}, count: ${tokens.length}, entries: ${groupSymbol(tier, group)}),`,
    );
  }
  lines.push('    ]', '}');
  return { path: posix.join(GENERATED_ROOT, 'DSTokenCatalog.swift'), contents: file(lines) };
}

// ---------------------------------------------------------------------------------------------
// Components
// ---------------------------------------------------------------------------------------------

interface SpecExample {
  readonly id: string;
  readonly props: readonly (readonly [string, unknown])[];
  readonly surface: string | null;
  readonly backdrop: string | null;
  readonly grid: readonly string[];
  readonly schemes: readonly string[];
  readonly description: string | null;
}

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v);
}

function propValue(value: unknown): string {
  if (typeof value === 'string') return `.string(${swiftString(value)})`;
  if (typeof value === 'number') return `.number(${Number.isInteger(value) ? `${value}` : `${value}`})`;
  if (typeof value === 'boolean') return `.bool(${value ? 'true' : 'false'})`;
  if (Array.isArray(value)) return `.list([${value.map(propValue).join(', ')}])`;
  if (isRecord(value)) {
    const pairs = Object.entries(value).map(([k, v]) => `DSPropValue.Pair(${swiftString(k)}, ${propValue(v)})`);
    return `.map([${pairs.join(', ')}])`;
  }
  return '.unknown';
}

/** The spec's props of `type: action`, which a harness must stage with a handler (see `actionsOf`). */
function actionPropsOf(spec: SpecRow): string[] {
  const raw = spec.doc.value?.['props'];
  if (!Array.isArray(raw)) return [];
  const names: string[] = [];
  for (const item of raw) {
    if (!isRecord(item)) continue;
    if (item['type'] !== 'action') continue;
    const name = item['name'];
    if (typeof name === 'string') names.push(name);
  }
  return names;
}

function examplesOf(spec: SpecRow): SpecExample[] {
  const raw = spec.doc.value?.['examples'];
  if (!Array.isArray(raw)) return [];
  const out: SpecExample[] = [];
  for (const item of raw) {
    if (!isRecord(item)) continue;
    const id = item['id'];
    if (typeof id !== 'string') continue;
    const props = isRecord(item['props']) ? Object.entries(item['props']) : [];
    const grid = Array.isArray(item['grid']) ? item['grid'].filter((g): g is string => typeof g === 'string') : [];
    const schemes = Array.isArray(item['schemes'])
      ? item['schemes'].filter((s): s is string => typeof s === 'string')
      : ['light', 'dark'];
    out.push({
      id,
      props,
      surface: typeof item['surface'] === 'string' ? item['surface'] : null,
      backdrop: typeof item['backdrop'] === 'string' ? item['backdrop'] : null,
      grid,
      schemes,
      description: typeof item['description'] === 'string' ? item['description'] : null,
    });
  }
  return out;
}

function platformNotesOf(spec: SpecRow): readonly (readonly [string, string])[] {
  const notes = spec.doc.value?.['notes'];
  if (!isRecord(notes)) return [];
  const platform = notes['platform'];
  if (!isRecord(platform)) return [];
  return Object.entries(platform)
    .filter((e): e is [string, string] => typeof e[1] === 'string')
    .filter(([key]) => (PLATFORMS as readonly string[]).includes(key));
}

function stringField(spec: SpecRow, field: string): string | null {
  const value = spec.doc.value?.[field];
  return typeof value === 'string' ? value.trim() : null;
}

/** `implemented` of the two Swift manifests, keyed by component name → platform → version. */
export function appleImplemented(reader: SourceReader, problems: string[]): Map<string, Map<string, number>> {
  const out = new Map<string, Map<string, number>>();
  for (const manifest of MANIFESTS) {
    if (manifest.stack !== 'swiftui') continue;
    if (!reader.exists(manifest.path)) {
      problems.push(`${manifest.path} is missing`);
      continue;
    }
    const parsed = parseManifest(reader.readText(manifest.path), manifest.syntax);
    for (const problem of parsed.problems) problems.push(`${manifest.path}:${problem.line} ${problem.message}`);
    for (const entry of parsed.entries) {
      const versions = out.get(entry.name) ?? new Map<string, number>();
      for (const version of entry.versions) versions.set(version.platform, version.version);
      out.set(entry.name, versions);
    }
  }
  return out;
}

export interface ComponentCatalog {
  readonly catalog: OutputFile;
  readonly bindings: OutputFile;
  /** The components this build implements on at least one Apple platform, in spec order. */
  readonly implementedNames: readonly string[];
}

function repositoryUrl(reader: SourceReader): string {
  const pkg = JSON.parse(reader.readText(TOKENS_PACKAGE)) as { repository?: { url?: string } };
  const url = pkg.repository?.url ?? '';
  return url.replace(/^git\+/, '').replace(/\.git$/, '');
}

export function renderComponentCatalog(reader: SourceReader, problems: string[]): ComponentCatalog {
  const { specs, diagnostics } = readSpecs(reader);
  for (const d of diagnostics) problems.push(`${d.file ?? '?'}: ${d.message}`);
  const implemented = appleImplemented(reader, problems);

  const lines: string[] = [
    header('spec/components, spec/patterns and the Swift implementation manifests'),
    '//',
    '// Every spec is a row, implemented or not, so the app can never silently omit one: the support level',
    '// comes from the spec, the implemented version from `DSComponentsManifest`/`DSChartsManifest`, and the',
    '// examples are the spec\'s own `examples[]` with the props as the spec writes them.',
    'import SwiftUI',
    '',
    'extension DSShowcaseCatalog {',
    `    /// Where the app links a spec, the gallery and the parity report.`,
    `    public static let repositoryURL = ${swiftString(repositoryUrl(reader))}`,
    '',
  ];

  const implementedNames: string[] = [];
  const entryLines: string[] = [];
  for (const spec of specs) {
    const versions = implemented.get(spec.name) ?? new Map<string, number>();
    const apple = APPLE_PLATFORMS.filter((p) => versions.has(p));
    const isPattern = LAYER_MANIFEST[spec.layer] === null;
    if (apple.length > 0 && !isPattern) implementedNames.push(spec.name);
    const platforms = [...spec.platforms.entries()].map(([p, s]) => `(${swiftString(p)}, .${s})`);
    const implementedPairs = apple.map((p) => `(${swiftString(p)}, ${versions.get(p) ?? 0})`);
    const examples = examplesOf(spec);
    // Every `type: action` prop of the spec. The web harness injects a no-op for each of these
    // (`web/apps/showcase/src/sections/Components.tsx`); Apple stages them through
    // `DSSpecExample.handler(_:)`, so a Card example draws the open glyph its baseline shows
    // (Card.yaml behavior 4) instead of silently staging an unpressable card.
    const actionProps = actionPropsOf(spec);
    lines.push(
      `    static let spec${spec.name}: DSComponentEntry = DSComponentEntry(`,
      `            name: ${swiftString(spec.name)},`,
      `            layer: ${swiftString(spec.layer)},`,
      `            summary: ${swiftString(stringField(spec, 'summary') ?? '')},`,
      `            since: ${optionalString(stringField(spec, 'since'))},`,
      `            specVersion: ${spec.specVersion},`,
      `            specPath: ${swiftString(spec.file)},`,
      `            isPattern: ${isPattern ? 'true' : 'false'},`,
      `            platforms: [${platforms.join(', ')}],`,
      `            implemented: [${implementedPairs.join(', ')}],`,
      `            platformNotes: [${platformNotesOf(spec).map(([k, v]) => `(${swiftString(k)}, ${swiftString(v)})`).join(', ')}],`,
      '            examples: [',
    );
    for (const example of examples) {
      const props = example.props.map(([k, v]) => `(${swiftString(k)}, ${propValue(v)})`);
      lines.push(
        `                DSSpecExample(` +
          `id: ${swiftString(example.id)}, ` +
          `props: [${props.join(', ')}], ` +
          `surface: ${optionalString(example.surface)}, ` +
          `backdrop: ${optionalString(example.backdrop)}, ` +
          `grid: [${example.grid.map(swiftString).join(', ')}], ` +
          `schemes: [${example.schemes.map(swiftString).join(', ')}], ` +
          `actions: [${actionProps.map(swiftString).join(', ')}], ` +
          `summary: ${optionalString(example.description)}),`,
      );
    }
    lines.push('            ]', '    )', '');
    entryLines.push(`        spec${spec.name},`);
  }
  lines.push('    public static let components: [DSComponentEntry] = [', ...entryLines, '    ]', '}');

  const bindingLines: string[] = [
    header('the Swift implementation manifests'),
    '//',
    '// One renderer per component this build implements on Apple. A component that lands in',
    '// `DSComponentsManifest.implemented` appears here on the next generate, and `DSShowcase` then does not',
    '// compile until `DS<Name>Renderer` exists — which is how the showcase cannot go stale without saying so.',
    'import SwiftUI',
    '',
    'extension DSShowcaseRenderers {',
    '    static let generated: [String: any DSExampleRenderer] = [',
    ...implementedNames.map((name) => `        ${swiftString(name)}: DS${name}Renderer(),`),
    '    ]',
    '}',
  ];

  return {
    catalog: { path: posix.join(GENERATED_ROOT, 'DSShowcaseCatalog.swift'), contents: file(lines) },
    bindings: { path: posix.join(GENERATED_ROOT, 'DSShowcaseBindings.swift'), contents: file(bindingLines) },
    implementedNames,
  };
}

/** Both catalogues and the renderer bindings, as the files a build would write. */
export function renderCatalogs(reader: SourceReader): CatalogResult {
  const problems: string[] = [];
  const tokens = renderTokenCatalog(reader, problems);
  const components = renderComponentCatalog(reader, problems);
  const files = [tokens, components.catalog, components.bindings].sort((a, b) => (a.path < b.path ? -1 : 1));
  return { files, problems };
}
