// The Xcode project for the showcase app (docs/showcase.md).
//
// SwiftPM cannot build an app bundle, so the app needs a project. It is written per run and gitignored, for the
// same reason `fixtures/swiftui-app`'s is (ADR-0014): the only thing in it that could drift is the package
// reference, and the sources beside it are committed. One target builds for the iOS simulator, the iPhone and
// the Mac from the one shared view layer, and links the local package's `DSShowcase` product.
import { existsSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';

/** Repository-relative home of the app: the shell, the library sources and the generated project. */
export const SHOWCASE_DIR = 'swift/Showcase';
export const APP_NAME = 'PrismShowcase';
/** The synchronized group, relative to the project directory. */
export const APP_SOURCES = 'App/PrismShowcase';
export const BUNDLE_ID = 'com.example.prism.showcase';
/** The one product the app links; it brings DSComponents, DSCore, DSTokens and DSIcons with it. */
export const PRODUCT = 'DSShowcase';

/** 24-character object ids, stable so a regenerated project is byte-identical. */
const ID = (n: number): string => `5H0WCA5E0000${n.toString(16).toUpperCase().padStart(12, '0')}`;
const OBJ = {
  project: ID(1),
  mainGroup: ID(2),
  productsGroup: ID(3),
  target: ID(4),
  productRef: ID(5),
  sources: ID(6),
  frameworks: ID(7),
  resources: ID(8),
  projectConfigs: ID(9),
  targetConfigs: ID(10),
  projectDebug: ID(11),
  projectRelease: ID(12),
  targetDebug: ID(13),
  targetRelease: ID(14),
  syncGroup: ID(15),
  package: ID(16),
  productDependency: ID(17),
  buildFile: ID(18),
} as const;

/** A pbxproj value, quoted whenever it is not a bare identifier. */
function value(text: string): string {
  return /^[A-Za-z0-9_.]+$/.test(text) ? text : `"${text.replace(/["\\]/gu, '\\$&')}"`;
}

/**
 * One target for three platforms. `SDKROOT = auto` with an explicit `SUPPORTED_PLATFORMS` is what an Xcode
 * multiplatform app uses; the deployment targets are the floors `Package.swift` declares (ADR-0003). Ad-hoc
 * signing (`-`) rather than no signing at all, because an unsigned binary does not launch on Apple silicon.
 */
const BUILD_SETTINGS = [
  'ALWAYS_SEARCH_USER_PATHS = NO',
  'ASSETCATALOG_COMPILER_GENERATE_ASSET_SYMBOL_EXTENSIONS = YES',
  'CLANG_ENABLE_MODULES = YES',
  'CODE_SIGN_IDENTITY = "-"',
  'CODE_SIGN_STYLE = Manual',
  'CODE_SIGNING_REQUIRED = NO',
  'DEVELOPMENT_TEAM = ""',
  'ENABLE_HARDENED_RUNTIME = NO',
  'ENABLE_USER_SCRIPT_SANDBOXING = YES',
  'GENERATE_INFOPLIST_FILE = YES',
  'INFOPLIST_KEY_CFBundleDisplayName = "Prism showcase"',
  'INFOPLIST_KEY_UIApplicationSceneManifest_Generation = YES',
  'INFOPLIST_KEY_UILaunchScreen_Generation = YES',
  'INFOPLIST_KEY_UISupportedInterfaceOrientations = "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"',
  'INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad = "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"',
  'IPHONEOS_DEPLOYMENT_TARGET = 26.0',
  'MACOSX_DEPLOYMENT_TARGET = 26.0',
  `PRODUCT_BUNDLE_IDENTIFIER = ${BUNDLE_ID}`,
  'PRODUCT_NAME = "$(TARGET_NAME)"',
  'SDKROOT = auto',
  'SUPPORTED_PLATFORMS = "iphoneos iphonesimulator macosx"',
  'SUPPORTS_MACCATALYST = NO',
  'SWIFT_EMIT_LOC_STRINGS = YES',
  // The language mode and default isolation the package's UI targets use, so the shell compiles like the library.
  'SWIFT_DEFAULT_ACTOR_ISOLATION = MainActor',
  'SWIFT_VERSION = 6.0',
  'TARGETED_DEVICE_FAMILY = "1,2"',
];

export function projectFile(root: string, projectDir: string): string {
  const packagePath = relative(resolve(projectDir), resolve(root)) || '.';
  const settings = BUILD_SETTINGS.map((s) => `\t\t\t\t${s};`).join('\n');
  return `// !$*UTF8*$!
// Generated by tools/showcase/apple (docs/showcase.md). Do not edit: regenerate it.
{
	archiveVersion = 1;
	classes = {
	};
	objectVersion = 77;
	objects = {

/* Begin PBXBuildFile section */
		${OBJ.buildFile} /* ${PRODUCT} in Frameworks */ = {isa = PBXBuildFile; productRef = ${OBJ.productDependency} /* ${PRODUCT} */; };
/* End PBXBuildFile section */

/* Begin PBXFileReference section */
		${OBJ.productRef} /* ${APP_NAME}.app */ = {isa = PBXFileReference; explicitFileType = wrapper.application; includeInIndex = 0; path = ${APP_NAME}.app; sourceTree = BUILT_PRODUCTS_DIR; };
/* End PBXFileReference section */

/* Begin PBXFileSystemSynchronizedRootGroup section */
		${OBJ.syncGroup} /* ${APP_SOURCES} */ = {isa = PBXFileSystemSynchronizedRootGroup; path = ${value(APP_SOURCES)}; sourceTree = "<group>"; };
/* End PBXFileSystemSynchronizedRootGroup section */

/* Begin PBXFrameworksBuildPhase section */
		${OBJ.frameworks} /* Frameworks */ = {
			isa = PBXFrameworksBuildPhase;
			buildActionMask = 2147483647;
			files = (
				${OBJ.buildFile} /* ${PRODUCT} in Frameworks */,
			);
			runOnlyForDeploymentPostprocessing = 0;
		};
/* End PBXFrameworksBuildPhase section */

/* Begin PBXGroup section */
		${OBJ.mainGroup} = {
			isa = PBXGroup;
			children = (
				${OBJ.syncGroup} /* ${APP_SOURCES} */,
				${OBJ.productsGroup} /* Products */,
			);
			sourceTree = "<group>";
		};
		${OBJ.productsGroup} /* Products */ = {
			isa = PBXGroup;
			children = (
				${OBJ.productRef} /* ${APP_NAME}.app */,
			);
			name = Products;
			sourceTree = "<group>";
		};
/* End PBXGroup section */

/* Begin PBXNativeTarget section */
		${OBJ.target} /* ${APP_NAME} */ = {
			isa = PBXNativeTarget;
			buildConfigurationList = ${OBJ.targetConfigs} /* Build configuration list for PBXNativeTarget "${APP_NAME}" */;
			buildPhases = (
				${OBJ.sources} /* Sources */,
				${OBJ.frameworks} /* Frameworks */,
				${OBJ.resources} /* Resources */,
			);
			buildRules = (
			);
			dependencies = (
			);
			fileSystemSynchronizedGroups = (
				${OBJ.syncGroup} /* ${APP_SOURCES} */,
			);
			name = ${APP_NAME};
			packageProductDependencies = (
				${OBJ.productDependency} /* ${PRODUCT} */,
			);
			productName = ${APP_NAME};
			productReference = ${OBJ.productRef} /* ${APP_NAME}.app */;
			productType = "com.apple.product-type.application";
		};
/* End PBXNativeTarget section */

/* Begin PBXProject section */
		${OBJ.project} /* Project object */ = {
			isa = PBXProject;
			attributes = {
				BuildIndependentTargetsInParallel = 1;
				LastSwiftUpdateCheck = 2660;
				LastUpgradeCheck = 2660;
				TargetAttributes = {
					${OBJ.target} = {
						CreatedOnToolsVersion = 26.0;
					};
				};
			};
			buildConfigurationList = ${OBJ.projectConfigs} /* Build configuration list for PBXProject "${APP_NAME}" */;
			compatibilityVersion = "Xcode 15.0";
			developmentRegion = en;
			hasScannedForEncodings = 0;
			knownRegions = (
				en,
				Base,
			);
			mainGroup = ${OBJ.mainGroup};
			minimizedProjectReferenceProxies = 1;
			packageReferences = (
				${OBJ.package} /* Prism */,
			);
			preferredProjectObjectVersion = 77;
			productRefGroup = ${OBJ.productsGroup} /* Products */;
			projectDirPath = "";
			projectRoot = "";
			targets = (
				${OBJ.target} /* ${APP_NAME} */,
			);
		};
/* End PBXProject section */

/* Begin PBXResourcesBuildPhase section */
		${OBJ.resources} /* Resources */ = {
			isa = PBXResourcesBuildPhase;
			buildActionMask = 2147483647;
			files = (
			);
			runOnlyForDeploymentPostprocessing = 0;
		};
/* End PBXResourcesBuildPhase section */

/* Begin PBXSourcesBuildPhase section */
		${OBJ.sources} /* Sources */ = {
			isa = PBXSourcesBuildPhase;
			buildActionMask = 2147483647;
			files = (
			);
			runOnlyForDeploymentPostprocessing = 0;
		};
/* End PBXSourcesBuildPhase section */

/* Begin XCBuildConfiguration section */
		${OBJ.projectDebug} /* Debug */ = {
			isa = XCBuildConfiguration;
			buildSettings = {
				ONLY_ACTIVE_ARCH = YES;
				SWIFT_OPTIMIZATION_LEVEL = "-Onone";
			};
			name = Debug;
		};
		${OBJ.projectRelease} /* Release */ = {
			isa = XCBuildConfiguration;
			buildSettings = {
				SWIFT_COMPILATION_MODE = wholemodule;
			};
			name = Release;
		};
		${OBJ.targetDebug} /* Debug */ = {
			isa = XCBuildConfiguration;
			buildSettings = {
${settings}
			};
			name = Debug;
		};
		${OBJ.targetRelease} /* Release */ = {
			isa = XCBuildConfiguration;
			buildSettings = {
${settings}
			};
			name = Release;
		};
/* End XCBuildConfiguration section */

/* Begin XCConfigurationList section */
		${OBJ.projectConfigs} /* Build configuration list for PBXProject "${APP_NAME}" */ = {
			isa = XCConfigurationList;
			buildConfigurations = (
				${OBJ.projectDebug} /* Debug */,
				${OBJ.projectRelease} /* Release */,
			);
			defaultConfigurationIsVisible = 0;
			defaultConfigurationName = Release;
		};
		${OBJ.targetConfigs} /* Build configuration list for PBXNativeTarget "${APP_NAME}" */ = {
			isa = XCConfigurationList;
			buildConfigurations = (
				${OBJ.targetDebug} /* Debug */,
				${OBJ.targetRelease} /* Release */,
			);
			defaultConfigurationIsVisible = 0;
			defaultConfigurationName = Release;
		};
/* End XCConfigurationList section */

/* Begin XCLocalSwiftPackageReference section */
		${OBJ.package} /* XCLocalSwiftPackageReference ${value(packagePath)} */ = {
			isa = XCLocalSwiftPackageReference;
			relativePath = ${value(packagePath)};
		};
/* End XCLocalSwiftPackageReference section */

/* Begin XCSwiftPackageProductDependency section */
		${OBJ.productDependency} /* ${PRODUCT} */ = {
			isa = XCSwiftPackageProductDependency;
			productName = ${PRODUCT};
		};
/* End XCSwiftPackageProductDependency section */
	};
	rootObject = ${OBJ.project} /* Project object */;
}
`;
}

/** A shared scheme, so `xcodebuild -scheme PrismShowcase` works on a project nobody has opened. */
export function schemeFile(projectName: string): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<Scheme LastUpgradeVersion = "2660" version = "1.7">
   <BuildAction parallelizeBuildables = "YES" buildImplicitDependencies = "YES">
      <BuildActionEntries>
         <BuildActionEntry buildForTesting = "YES" buildForRunning = "YES" buildForProfiling = "YES" buildForArchiving = "YES" buildForAnalyzing = "YES">
            <BuildableReference
               BuildableIdentifier = "primary"
               BlueprintIdentifier = "${OBJ.target}"
               BuildableName = "${APP_NAME}.app"
               BlueprintName = "${APP_NAME}"
               ReferencedContainer = "container:${projectName}">
            </BuildableReference>
         </BuildActionEntry>
      </BuildActionEntries>
   </BuildAction>
   <LaunchAction buildConfiguration = "Debug" selectedDebuggerIdentifier = "Xcode.DebuggerFoundation.Debugger.LLDB" selectedLauncherIdentifier = "Xcode.DebuggerFoundation.Launcher.LLDB" launchStyle = "0" useCustomWorkingDirectory = "NO" ignoresPersistentStateOnLaunch = "NO" debugDocumentVersioning = "YES" debugServiceExtension = "internal" allowLocationSimulation = "YES">
      <BuildableProductRunnable runnableDebuggingMode = "0">
         <BuildableReference
            BuildableIdentifier = "primary"
            BlueprintIdentifier = "${OBJ.target}"
            BuildableName = "${APP_NAME}.app"
            BlueprintName = "${APP_NAME}"
            ReferencedContainer = "container:${projectName}">
         </BuildableReference>
      </BuildableProductRunnable>
   </LaunchAction>
   <AnalyzeAction buildConfiguration = "Debug">
   </AnalyzeAction>
   <ArchiveAction buildConfiguration = "Release" revealArchiveInOrganizer = "YES">
   </ArchiveAction>
</Scheme>
`;
}

/** Writes `swift/Showcase/PrismShowcase.xcodeproj` and returns its path. */
export function writeProject(root: string): string {
  const showcase = join(root, SHOWCASE_DIR);
  if (!existsSync(join(showcase, APP_SOURCES, `${APP_NAME}App.swift`))) {
    throw new Error(`${SHOWCASE_DIR}/${APP_SOURCES} is not there: the app's sources are committed, the project is not`);
  }
  const project = join(showcase, `${APP_NAME}.xcodeproj`);
  rmSync(project, { recursive: true, force: true });
  mkdirSync(join(project, 'xcshareddata', 'xcschemes'), { recursive: true });
  writeFileSync(join(project, 'project.pbxproj'), projectFile(root, showcase), 'utf8');
  writeFileSync(join(project, 'xcshareddata', 'xcschemes', `${APP_NAME}.xcscheme`), schemeFile(`${APP_NAME}.xcodeproj`), 'utf8');
  return project;
}
